Calibration read/write/load API
luxonis/depthai-core pull request #101
Opened 2021-04-08 16:14 UTC by saching13

Added 
- read/write api over xlink.
- Calibration Handler to load version 6 and 5 of EEPROM data along with manual setters and getters to get the camera intrinsic, extrinsic, distortion coeffs.

Next steps 
- Load EepromData Functionality (No flash)
- Stereo rectification getters
- Make stereo Node mode configurable by adding overloading rectification and other required stereo properties.

2021-04-08 16:15 UTC, saching13 commented
> Make stereo Node mode configurable by adding overloading rectification and other required stereo properties.
On this will do it on a different PR after we finish this, or I can do it after merging this in stereo fixes PR of @alex-luxonis

2021-04-10 06:34 UTC, themarpe requested changes
Initial review

2021-04-10 06:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +    auto matrix_conv = [](std::vector<float>& src, int startIdx) {
`matrixConv`

2021-04-10 06:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +    if(!jsonStream.good() || jsonStream.bad()) {
Doesn't `is_open` suffice?

2021-04-10 06:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +    std::cout << "Test here ------------" << std::endl;
To remove

2021-04-10 06:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +    std::cout << topLeftPixelId.x << " - " << bottomRightPixelId.y << std::endl;
To remove

2021-04-13 17:05 UTC, saching13 commented on examples/src/calibration_storer.cpp
> +
I wil change it to calibration_flash actually to match with function namings

2021-04-13 17:08 UTC, saching13 commented on include/depthai/device/CalibrationHandler.hpp
> +    void setBoardInfo(uint32_t version, bool swapLeftRightCam, std::string boardName, std::string boardRev);
Agree. Makes sense. Will remove it.
I was skeptical about adding it in the first place. And thought of deciding later.

2021-04-13 17:10 UTC, saching13 commented on src/device/CalibrationHandler.cpp
> +    if(!jsonStream.good() || jsonStream.bad()) {
if the user copies a corrupted file then it can still be opened and not have acceptable data. With that in mind I hadded this check.

2021-04-15 21:37 UTC, saching13 commented on include/depthai/device/CalibrationHandler.hpp
> +     * @brief Construct a new Calibration Handler object using the
Not sure. I know doxygen does.
Will check and sphinx fails will change it.

2021-04-15 21:58 UTC, saching13 commented on include/depthai/device/CalibrationHandler.hpp
> +    void setCameraIntrinsics(CameraBoardSocket cameraId, std::vector<std::vector<float>> intrinsics, int width, int height);
will use Size2f instead

2021-04-15 22:02 UTC, saching13 commented on src/device/Device.cpp
> +        return false;
```
if(res == 0) return true;
else return false;
```
I had done this. formatting changed it back to next line

2021-04-15 22:02 UTC, themarpe commented on include/depthai/device/CalibrationHandler.hpp
> +    void setCameraIntrinsics(CameraBoardSocket cameraId, std::vector<std::vector<float>> intrinsics, int width, int height);
The reason for tuple is that we use it in other parts of codebase as well (VideoEncoder, ColorCamera, ...) and in bindings, where you can simply pass a tuple to the function call from bindings.

But you can also do a Size2f along that IMO

2021-04-15 22:03 UTC, themarpe commented on src/device/Device.cpp
> +        return false;
Yeah - a bit unfortunate from clang formatting perspective - I haven't found a setting yet which would prevent this till now.

Then go with above rather

2021-04-22 14:48 UTC, themarpe requested changes

2021-04-22 14:48 UTC, themarpe commented on include/depthai/device/Device.hpp
> +    DeviceInfo getCurrentDeviceInfo();
Const and rename IMO - as the current context is implied from the object on which the function is called
```
DeviceInfo getDeviceInfo() const;
```

2021-04-22 14:48 UTC, themarpe commented on examples/CMakeLists.txt
> +dai_add_example(calibration_load src/calibration_load.cpp)
These should preferably be optional (or off by default) in the test suite though.
As otherwise everytime the tests are ran, the device will be reflashed.

2021-04-22 14:48 UTC, themarpe commented on examples/CMakeLists.txt
> +dai_add_example(calibration_load src/calibration_load.cpp)
As well as other intrusive examples:
```
dai_add_example(bootloader_example src/bootloader_example.cpp)
...
```

2021-04-22 14:48 UTC, themarpe commented on include/depthai/device/CalibrationHandler.hpp
> +     * @return std::vector<std::vector<float>> - repesents the 3x3 intrinsics matrix of the respective camera at the requested size and crop dimensions.
Check that these are actually parsed correctly by Python side as well. I'd suggest just making it in same manner as other code is (also for sake of consistency).
```
@returns Represents the 3x3 intrinsic matrix ...
```

Example:
```
    /**
     * Add a callback for device logging. The callback will be called from a separate thread with the LogMessage being passed.
     *
     * @param callback - Callback to call whenever a log message arrives
     * @return Id which can be used to later remove the callback
     */
    int addLogCallback(std::function<void(LogMessage)> callback);
```

2021-04-22 14:48 UTC, themarpe commented on include/depthai/device/CalibrationHandler.hpp
> +     * @return std::vector<std::vector<float>> - repesents the 3x3 intrinsics matrix of the respective camera at the requested size and crop dimensions.
^ this applies to the whole PR

2021-04-26 19:31 UTC, saching13 commented on include/depthai/device/CalibrationHandler.hpp
> +     * @return std::vector<std::vector<float>> - repesents the 3x3 intrinsics matrix of the respective camera at the requested size and crop dimensions.
But C++ users need to know the type right. Where users don't want to use the `auto`.

2021-04-28 22:37 UTC, themarpe commented on include/depthai/device/CalibrationHandler.hpp
> +     * @return std::vector<std::vector<float>> - repesents the 3x3 intrinsics matrix of the respective camera at the requested size and crop dimensions.
The type is in the function signature - not sure how doxygen displays that, but its still there.

2021-05-01 00:12 UTC, saching13 commented on include/depthai/device/CalibrationHandler.hpp
> +     * @return std::vector<std::vector<float>> - repesents the 3x3 intrinsics matrix of the respective camera at the requested size and crop dimensions.
Removed them

2021-05-02 15:34 UTC, themarpe requested changes
Remove unneeded commented code and address some left over TODOs.

Also not sure how sphinx renders:
```
@param cameraId - CameraId of the camera for which cameraModel Type is being updated.
```

The minus(-) between the parameter and description isn't used in other cases.

Same for @brief - usually not used.

Check https://developer.lsst.io/cpp/api-docs.html for reference

2021-05-02 15:34 UTC, themarpe commented on include/depthai/device/Device.hpp
> +    CalibrationHandler getCalibration();
I'd rename this to `readCalibration` instead - I think it's more of a counterpart to `flashCalibration`

2021-05-02 15:34 UTC, themarpe commented on include/depthai/pipeline/Pipeline.hpp
> +    void setCalibrationData(CalibrationHandler calib);
Add `CalibrationHandler getCalibrationData() const`

2021-05-02 15:34 UTC, themarpe commented on include/depthai/utility/matrixOps.hpp
> +        std::cerr << "Number of column of the first matrix should match with the number of rows of the second matrix " << std::endl;
IMO - Throw instead (or spdlog - we don't use plain stdout/stderr in other cases)

2021-05-02 15:34 UTC, themarpe commented on include/depthai/utility/matrixOps.hpp
> +{
Was Clangformat applied in this file?

2021-05-02 15:34 UTC, themarpe commented on include/depthai/utility/matrixOps.hpp
> +#pragma once
As this header is not public - move to `src/utility` instead (See: BootloaderHelper.cpp, etc...)

2021-05-02 15:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +        if(boardConfigStream.is_open()) {
Combine is_open with good || bad checks.
```
if(!file.is_open() || !file.good() || file.bad()){
    throw std::runtime_error("Calibration data file not found or corrupted");
}

// No need to do if again
std::ifstream boardConfigStream(boardConfigPath);

if(!boardConfigStream.is_open() || !boardConfigStream.good() || boardConfigStream.bad()) {
    throw std::runtime_error("BoardConfig file not found or corrupted");
}

// No need to do if again
nlohmann::json boardConfigData = nlohmann::json::parse(boardConfigStream);
...
```

2021-05-02 15:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +        std::vector<float> calibration_buff(versionSize / sizeof(float));
`calibrationBuff`

2021-05-02 15:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +        file.read(reinterpret_cast<char*>(calibration_buff.data()), fSize);
^ 
To be on the safe side
```
std::vector<float> calibrationBuff(std::istreambuf_iterator<char>(file), {});
```

2021-05-02 15:34 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +}
```
void CalibrationHandler::eepromToJsonFile(const std::string& destPath) const;
```

2021-05-03 18:00 UTC, saching13 commented on include/depthai/pipeline/Pipeline.hpp
> +    void setCalibrationData(CalibrationHandler calib);
Do we need to ?
User will be setting a `CalibrationHandler` object in the same script so would they be calling it back again from pipeline ?

2021-05-03 18:05 UTC, themarpe commented on include/depthai/pipeline/Pipeline.hpp
> +    void setCalibrationData(CalibrationHandler calib);
Might be needed in future, could be that a given pipeline is created somewhere else, etc...

2021-05-03 18:13 UTC, saching13 commented on include/depthai/pipeline/Pipeline.hpp
> +    void setCalibrationData(CalibrationHandler calib);
got it. 
For scenarios where it is not available should I throw an error or return an empty constructor of CalibrationHandler ?

2021-05-03 18:21 UTC, themarpe commented on include/depthai/pipeline/Pipeline.hpp
> +    void setCalibrationData(CalibrationHandler calib);
If default constructed CalibrationHandler makes sense in terms of contents / being able to detect its empty somehow, ..., then I'd go in that direction.

2021-05-03 18:30 UTC, saching13 commented on include/depthai/utility/matrixOps.hpp
> +{
I did and it didn't fix the space. 
Fixed manually now

2021-05-06 10:45 UTC, pawel-pieniazek commented on examples/src/calibration_flash.cpp
> +    calibData.setFov(dai::CameraBoardSocket::LEFT, 80.55);
why FOV of left and right camera are different?

2021-05-06 23:09 UTC, saching13 commented on examples/src/calibration_flash.cpp
> +    calibData.setFov(dai::CameraBoardSocket::LEFT, 80.55);
Calibration Data in the example is made up to show as an example.
Writing an actual calibration script in python which calibrates and writes it to the device.

2021-05-12 18:35 UTC, alex-luxonis commented
The tests using parameters (NN blob path) are failing:
```
      Start  8: camera_mobilenet
 8/30 Test  #8: camera_mobilenet ....................***Failed    0.50 sec
statusfound -P
-- arguments: /home/alex/depthai-python/depthai-core/build/examples/camera_mobilenet;ON;
terminate called after throwing an instance of 'std::logic_error'
  what():  BlobReader error: File does not seem to be a supported neural network blob
-- After process executed,  produced the following exit code: Subprocess aborted
```
`ON` gets passed as an argument to the program, and it overrides the blob path.

2021-05-12 19:39 UTC, szabi-luxonis commented
> The tests using parameters (NN blob path) are failing:
> 
>       Start  8: camera_mobilenet
>  8/30 Test  #8: camera_mobilenet ....................***Failed    0.50 sec
> statusfound -P
> -- arguments: /home/alex/depthai-python/depthai-core/build/examples/camera_mobilenet;ON;
> terminate called after throwing an instance of 'std::logic_error'
>   what():  BlobReader error: File does not seem to be a supported neural network blob
> -- After process executed,  produced the following exit code: Subprocess aborted
>  Save
> ON gets passed as an argument to the program, and it overrides the blob path.
> 
> Yeah. I have seen that. Didn't realize ON was the reason. Weird that it overrides in test but not in actual example. Any idea why ?

Myabe it should be skipped https://github.com/luxonis/depthai-core/pull/101/files#diff-940e5356fa1137e646ea135a6f68cacbfad4fe7124c3a69163468f588acf9283R24 here

2021-05-13 02:15 UTC, saching13 commented
> > The tests using parameters (NN blob path) are failing:
> > ```
> >   Start  8: camera_mobilenet
> > ```
> > 
> > ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > 8/30 Test  #8: camera_mobilenet ....................***Failed    0.50 sec
> > statusfound -P
> > -- arguments: /home/alex/depthai-python/depthai-core/build/examples/camera_mobilenet;ON;
> > terminate called after throwing an instance of 'std::logic_error'
> > what():  BlobReader error: File does not seem to be a supported neural network blob
> > -- After process executed,  produced the following exit code: Subprocess aborted
> > Save
> > ON gets passed as an argument to the program, and it overrides the blob path.
> > Yeah. I have seen that. Didn't realize ON was the reason. Weird that it overrides in test but not in actual example. Any idea why ?
> 
> Myabe it should be skipped [here](https://github.com/luxonis/depthai-core/pull/101/files#diff-940e5356fa1137e646ea135a6f68cacbfad4fe7124c3a69163468f588acf9283R24)

Thanks. Fixed it.

2021-05-13 18:00 UTC, themarpe approved these changes
LGTM

2021-05-13 18:04 UTC, alex-luxonis commented on examples/src/bootloader_example.cpp
> +    if(argc = 2) {
Typo here? `=` -> `==`

2021-05-13 19:46 UTC, szabi-luxonis requested changes
Examples are inconsistent with the python ones (there are examples that are not in depthai-python)

2021-05-13 19:50 UTC, saching13 commented
> Examples are inconsistent with the python ones (there are examples that are not in depthai-python)

On this. Should I add calibration_load and calibration_flash example in C++ and python ? 
`Cacalibration_flash` would be done by calibration script so I was thinking of removing that one. 
And integrate `calibration_load` option inside `stereo` mode example. 

Thoughts ? @szabi-luxonis

2021-05-14 01:48 UTC, szabi-luxonis commented
> > Examples are inconsistent with the python ones (there are examples that are not in depthai-python)
> 
> On this. Should I add calibration_load and calibration_flash example in C++ and python ?
> `Cacalibration_flash` would be done by calibration script so I was thinking of removing that one.
> And integrate `calibration_load` option inside `stereo` mode example.
> 
> Thoughts ? @szabi-luxonis

Yes, better remove calib_flash because it can mess up calibration data if the user runs it accidentally.
Calibration load you could integrate in this experiment : https://github.com/luxonis/depthai-experiments/tree/master/gen2-camera-demo
since pcl requires it.

2021-05-14 19:54 UTC, saching13 commented
> > > Examples are inconsistent with the python ones (there are examples that are not in depthai-python)
> > 
> > 
> > On this. Should I add calibration_load and calibration_flash example in C++ and python ?
> > `Cacalibration_flash` would be done by calibration script so I was thinking of removing that one.
> > And integrate `calibration_load` option inside `stereo` mode example.
> > Thoughts ? @szabi-luxonis
> 
> Yes, better remove calib_flash because it can mess up calibration data if the user runs it accidentally.
> Calibration load you could integrate in this experiment : https://github.com/luxonis/depthai-experiments/tree/master/gen2-camera-demo
> since pcl requires it, but also add a standalone example.

Yes. Adding the read in `gen2-camera-demo` is good idea. I already have local changes on that. 
But `calibration_load` example takes calibration data as input to the pipeline and when this is done calibration data in EEPROM will be overloaded with the calibration data in the pipeline. 
Examples for this falls under stereo setup as of now.

2021-05-15 19:57 UTC, szabi-luxonis commented
> > > > Examples are inconsistent with the python ones (there are examples that are not in depthai-python)
> > > 
> > > 
> > > On this. Should I add calibration_load and calibration_flash example in C++ and python ?
> > > `Cacalibration_flash` would be done by calibration script so I was thinking of removing that one.
> > > And integrate `calibration_load` option inside `stereo` mode example.
> > > Thoughts ? @szabi-luxonis
> > 
> > 
> > Yes, better remove calib_flash because it can mess up calibration data if the user runs it accidentally.
> > Calibration load you could integrate in this experiment : https://github.com/luxonis/depthai-experiments/tree/master/gen2-camera-demo
> > since pcl requires it, but also add a standalone example.
> 
> Yes. Adding the read in `gen2-camera-demo` is good idea. I already have local changes on that.
> But `calibration_load` example takes calibration data as input to the pipeline and when this is done calibration data in EEPROM will be overloaded with the calibration data in the pipeline.
> Examples for this falls under stereo setup as of now.

Then what's the difference between load and flash?

2021-05-16 02:49 UTC, saching13 commented
> > > > > Examples are inconsistent with the python ones (there are examples that are not in depthai-python)
> 
> > > > 
> 
> > > > 
> 
> > > > On this. Should I add calibration_load and calibration_flash example in C++ and python ?
> 
> > > > `Cacalibration_flash` would be done by calibration script so I was thinking of removing that one.
> 
> > > > And integrate `calibration_load` option inside `stereo` mode example.
> 
> > > > Thoughts ? @szabi-luxonis
> 
> > > 
> 
> > > 
> 
> > > Yes, better remove calib_flash because it can mess up calibration data if the user runs it accidentally.
> 
> > > Calibration load you could integrate in this experiment : https://github.com/luxonis/depthai-experiments/tree/master/gen2-camera-demo
> 
> > > since pcl requires it, but also add a standalone example.
> 
> > 
> 
> > Yes. Adding the read in `gen2-camera-demo` is good idea. I already have local changes on that.
> 
> > But `calibration_load` example takes calibration data as input to the pipeline and when this is done calibration data in EEPROM will be overloaded with the calibration data in the pipeline.
> 
> > Examples for this falls under stereo setup as of now.
> 
> 
> 
> Then what's the difference between load and flash?

Flash writes to eeprom.
Load in pipeline loads calibration for that execution instance. This is replacement for loadCalibration() in stereo. 
And the reason for removing this from stereo is because it loads complete calibration which can be used by other nodes. So it's not specific to stereo node. 
In stereo node in an another PR we should add separate function to overload only rectification patameters and intrinsics if users are doing it from host or swapping camera modules and testing etc.

2021-05-18 02:02 UTC, szabi-luxonis commented
> In stereo node in an another PR we should add separate function to overload only rectification patameters and intrinsics if users are doing it from host or swapping camera modules and testing etc.

There is already `loadCalibrationData` in stereo node.

2021-05-18 16:05 UTC, saching13 commented
> > In stereo node in an another PR we should add separate function to overload only rectification patameters and intrinsics if users are doing it from host or swapping camera modules and testing etc.
> 
> There is already `loadCalibrationData` in stereo node.

We decided to deprecate that. The reason being that calibration data is for the whole device and not specific to the stereo node. 
Going forward there will be other nodes and more features under ImageManip I think which needs this data. 
And as of stereo node it doesn't need the complete calibration. if the user is sending overloaded calibration for stereo there should be no need to send the complete structure of calibration data. Having separate `overloadLeftRectification(std::vector<std::vector<float>) / overloadRightRectification(std::vector<std::vector<float>)` makes it more intuitive for users to try and play with it.

2021-05-28 10:08 UTC, themarpe requested changes

2021-05-28 10:08 UTC, themarpe commented on examples/src/calibration_flash.cpp
> +    std::string calib_pth(CALIB_PATH);
calibPath

2021-05-28 10:08 UTC, themarpe commented on examples/src/calibration_load.cpp
> +    std::string calib_pth(CALIB_PATH);
calibPath

2021-05-28 10:08 UTC, themarpe commented on include/depthai/device/Device.hpp
> +#include "depthai/device/CalibrationHandler.hpp"
Move under `//project` group of includes

2021-05-28 10:08 UTC, themarpe commented on src/device/Device.cpp
> +    // std::unique_lock<std::mutex> lock(this->rpcMutex);
Remove this line

2021-05-29 00:34 UTC, saching13 reviewed
@szabi-luxonis  and @themarpe Can you cross-check and approve it if all good?

2021-05-29 03:10 UTC, alex-luxonis approved these changes

2021-05-29 16:58 UTC, saching13 commented
Cannot merge this. Need approval from @szabi-luxonis and @themarpe

2021-05-30 04:03 UTC, merged

2021-05-30 10:34 UTC, alex-luxonis commented
It appears this firmware fixes the slight shifting issue between RGB and depth, with RGB-depth alignment enabled. :+1:

2021-05-30 16:57 UTC, Luxonis-Brandon commented
Sweet!