VIO & SLAM Host Nodes
luxonis/depthai-core pull request #1012
Opened 2024-04-30 12:06 UTC by Serafadam

- Adds Basalt VIO node
- Adds RTABMap VO/SLAM nodes
- Adds TransformData datatype

2024-05-27 11:02 UTC, moratom requested changes
Thanks @Serafadam!

Excited to see try this out, but it seems like it doesn't build on my Ubuntu20.04 yet:

```
CMake Error at CMakeLists.txt:98 (find_package):
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.4".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: 3.3.7
    /lib/cmake/eigen3/Eigen3Config.cmake, version: 3.3.7



-- Configuring incomplete, errors occurred!
make[2]: *** [CMakeFiles/basalt-headers-Release.dir/build.make:92: basalt-headers-Release-prefix/src/basalt-headers-Release-stamp/basalt-headers-Release-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/basalt-headers-Release.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/matevz/.hunter/_Base/1292e4d/a3a48bb/7eb72a0/Build/basalt-headers
[hunter ** FATAL ERROR **] [Directory:/home/matevz/Luxonis/Core/depthai-core/cmake]

------------------------------ ERROR -----------------------------
    https://hunter.readthedocs.io/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/matevz/.hunter/_Base/Download/Hunter/0.24.18/1292e4d/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/matevz/.hunter/_Base/Download/Hunter/0.24.18/1292e4d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/matevz/.hunter/_Base/Download/Hunter/0.24.18/1292e4d/Unpacked/cmake/modules/hunter_download.cmake:623 (hunter_fatal_error)
  /home/matevz/.hunter/_Base/Download/Hunter/0.24.18/1292e4d/Unpacked/cmake/modules/hunter_add_package.cmake:53 (hunter_download)
  cmake/depthaiDependencies.cmake:115 (hunter_add_package)
  CMakeLists.txt:177 (include)


-- Configuring incomplete, errors occurred!

```

by running:
`cmake -S. -Bbuild -D'BUILD_SHARED_LIBS=ON' -D'DEPTHAI_BUILD_EXAMPLES=ON' -D'DEPTHAI_RTABMAP_SUPPORT=ON' -D'DEPTHAI_PCL_SUPPORT=ON' -D'DEPTHAI_BASALT_SUPPORT=ON'`

Can we make CMake compile `Eigen` instead of taking the one from the system?

2024-05-27 11:02 UTC, moratom commented on src/rtabmap/RTABMapVIO.cpp
> +    imuLocalTransform = rtabmap::Transform::getIdentity() * imuLocalTransform;
We moved this to FW now right?

2024-05-27 13:57 UTC, Serafadam commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +    std::vector<Point3f> colors;
Sure, that was only to temporarily check PCL publishing, this can be removed for now

2024-05-27 13:58 UTC, Serafadam commented on src/rtabmap/RTABMapSLAM.cpp
> +}
It's just used to obtain RTABMap calibration model, I'll update the method signature.

2024-05-27 13:58 UTC, Serafadam commented on src/rtabmap/RTABMapVIO.cpp
> +    imuLocalTransform = rtabmap::Transform::getIdentity() * imuLocalTransform;
Yup, that was mostly left for reference purposes, removed now in place of correct method call

2024-05-27 14:00 UTC, Serafadam commented on examples/CMakeLists.txt
> +endif()
ATM it was easier to set up for these examples, @themarpe said that it is okay for now just for those examples

2024-05-27 16:24 UTC, moratom commented on examples/CMakeLists.txt
> +endif()
Right, synced with Martin on that today too, let's keep it this way until we have our viewer ready.

2024-06-05 15:25 UTC, themarpe requested changes

2024-06-05 15:25 UTC, themarpe commented on include/depthai/basalt/BasaltVIO.hpp
> +    tbb::concurrent_bounded_queue<basalt::PoseVelBiasState<double>::Ptr> outStateQueue;
Do we need to bring in TBB + as a downwards dependency (as its in public header)?
If not, move to Impl and hide

Also, why raw pointer instead of managed one (unique / shared)?

2024-06-05 15:25 UTC, themarpe commented on include/depthai/rtabmap/RTABMapSLAM.hpp
> +    rtabmap::OccupancyGrid* grid;
unique_ptr or shared_ptr

2024-06-05 15:25 UTC, themarpe commented on include/depthai/rtabmap/RTABMapVIO.hpp
> +    std::map<double, cv::Vec4f> rotBuffer_;
Naming - private is known by IDE/compiler, no need for underscore postfix

2024-06-06 16:21 UTC, jakaskerl commented on include/depthai/rtabmap/RTABMapVIO.hpp
> +    Input input{*this, {.name = "in", .types = {{DatatypeEnum::MessageGroup, true}}}};
Is this supposed to be Sync input?

2024-06-07 12:02 UTC, Serafadam commented on examples/VSLAM/basalt_dai_vio.cpp
> +};
Updated

2024-06-07 12:02 UTC, Serafadam commented on include/depthai/pipeline/datatype/TransformData.hpp
> +
Changed to 4x4x matrix

2024-06-07 12:02 UTC, Serafadam commented on src/rtabmap/RTABMapSLAM.cpp
> +    for(auto& msg : *group) {
Added check

2024-06-07 12:02 UTC, Serafadam commented on src/rtabmap/RTABMapSLAM.cpp
> +    }
Updated to use sync node & fixed inputs

2024-06-07 12:03 UTC, Serafadam commented on src/rtabmap/RTABMapVIO.cpp
> +    }
Changed to unique ptr

2024-06-07 12:03 UTC, Serafadam commented on src/rtabmap/RTABMapSLAM.cpp
> +}
Updated method signature

2024-06-07 12:04 UTC, Serafadam commented on CMakeLists.txt
> +set(THIRDPARTY_OPENCV_LIBRARIES "mp4v2::mp4v2" CACHE STRING "Optional libraries to link OpenCV support, e.g. TBB::tbb")
Removed, although it still outputs linker errors (tested on different machines)

2024-06-07 12:04 UTC, Serafadam commented on include/depthai/rtabmap/RTABMapSLAM.hpp
> +    }
Updated method signature

2024-06-07 12:05 UTC, Serafadam commented on src/basalt/BasaltVIO.cpp
> +        int exposure_ms = std::chrono::duration_cast<std::chrono::milliseconds>(exposure).count();
Updated

2024-06-07 12:05 UTC, Serafadam commented on cmake/depthaiDependencies.cmake
Updated

2024-06-07 12:05 UTC, Serafadam commented on include/depthai/rtabmap/RTABMapVIO.hpp
> +     */
Removed

2024-06-07 12:06 UTC, Serafadam commented on src/rtabmap/CalibrationHandler.cpp
> +
Changed method signature to accept different stereo pair sockets

2024-06-07 12:06 UTC, Serafadam commented on src/rtabmap/CalibrationHandler.cpp
> +    return rtabmap::StereoCameraModel(eepromData.boardName, fx, fy, cx, cy, baseline, poseToCamera, cv::Size(width, height));
This was due to RTABMap's convention where middle camera is the origin, changed to localTransform

2024-06-07 12:06 UTC, Serafadam commented on src/rtabmap/RTABMapSLAM.cpp
> +}
Removed

2024-06-07 12:06 UTC, Serafadam commented on src/rtabmap/RTABMapSLAM.cpp
> +            std::cout << "Database saved" << std::endl;
Updated

2024-06-07 12:06 UTC, Serafadam commented on CMakeLists.txt
>  endif()
Added combined target

2024-06-07 12:08 UTC, Serafadam commented on include/depthai/basalt/BasaltVIO.hpp
> +    tbb::concurrent_bounded_queue<basalt::PoseVelBiasState<double>::Ptr> outStateQueue;
Added forward declarations of those classes, the types are tied to Basalt interface

2024-06-07 12:08 UTC, Serafadam commented on include/depthai/rtabmap/RTABMapSLAM.hpp
> +    rtabmap::OccupancyGrid* grid;
Updated

2024-06-07 12:08 UTC, Serafadam commented on include/depthai/rtabmap/RTABMapVIO.hpp
> +    std::map<double, cv::Vec4f> rotBuffer_;
Updated

2024-06-07 12:08 UTC, Serafadam commented on include/depthai/rtabmap/RTABMapVIO.hpp
> +    Input input{*this, {.name = "in", .types = {{DatatypeEnum::MessageGroup, true}}}};
Changed name to inSync, moved to private as users won't need to access it

2024-06-26 13:44 UTC, themarpe requested changes
Couple of things:
 
1. Stdout prints

> Numerical failure in backsubstitution

remove from being printed to stdout, add to log or just remove

3.  RGB-D SLAM

Use PointCloud to pack RGBD data, match pcl binary format.

3. CTRL+C doesn't cleanup the example properly

@moratom  for wrapping `run()` to catch "QueueException" exception to cleanup gracefully by default

@Serafadam  fixup ~BasaltVIO() destructor, to not "deadlock" when cleaning up

4.

Modify rerun_node py/hpp to following:
```
rr.log("world/camera/image", rr.Pinhole(resolution=[imgFrame.getWidth(), getHeight()], focal_length=focal_calib_data, camera_xyz=rr.ViewCoordinates.FLU))
```

6. Add requirements for `rerun_sdk==0.15.1` as optional, and fail examples that require it

2024-07-03 10:02 UTC, moratom commented on src/pipeline/datatype/PointCloudData.cpp
> +
What happens if the underlying points are not RGB though? Likely garbage data right?

2024-07-03 10:06 UTC, moratom commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +    std::vector<Point3fRGB> getPointsRGB();
I think we can return an optional here or throw in case the pointcloud is not RGB

2024-07-03 10:31 UTC, themarpe commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +    std::vector<Point3fRGB> getPointsRGB();
Or vector is empty is IMO fine

2024-07-03 10:31 UTC, themarpe commented on bindings/python/pyproject.toml
> +requires = ["setuptools", "wheel", "mypy<=1.3.0", "numpy==1.18.5", "cmake==3.25"]
can be removed now /w numpyv2 support

2024-07-03 10:38 UTC, Serafadam commented on src/pipeline/datatype/PointCloudData.cpp
> +
For now I assumed that we can return just regular XYZ points without color data

2024-07-04 08:48 UTC, Serafadam commented on src/pipeline/datatype/PointCloudData.cpp
> +
Changed to throw error in this case

2024-07-04 10:13 UTC, Serafadam commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +    std::vector<Point3fRGB> getPointsRGB();
Changed to throwing

2024-07-11 16:18 UTC, moratom commented on bindings/python/cmake/pybind11-mkdoc.cmake
> +    #file(TOUCH_NOCREATE ${mkdoc_headers})
Can we add this back now that it's filtered?

2024-07-11 16:20 UTC, moratom commented on bindings/python/src/pipeline/PipelineBindings.cpp
> +        .def("getDefaultDevice", &Pipeline::getDefaultDevice, DOC(dai, Pipeline, getDefaultDevice))
Already added in v3_develop

2024-07-12 07:10 UTC, Serafadam commented on bindings/python/src/pipeline/PipelineBindings.cpp
> +        .def("getDefaultDevice", &Pipeline::getDefaultDevice, DOC(dai, Pipeline, getDefaultDevice))
removed

2024-07-12 07:11 UTC, Serafadam commented on bindings/python/cmake/pybind11-mkdoc.cmake
> +    #file(TOUCH_NOCREATE ${mkdoc_headers})
brought back

2024-07-12 09:08 UTC, moratom approved these changes

2024-07-12 09:16 UTC, merged