Add input queues to the new API
luxonis/depthai-core pull request #1029
Opened 2024-05-26 15:15 UTC by lnotspotl

This PR renames the old `createQueue` method to `createOutputQueue` for the `Output` class. The old function stayed in the code, however it was marked as deprecated.

Additionally, a new class, `InputQueue` was introduced, allowing for communication between host and the connected device. A new method called `createInputQueue` was added to the `Input` class. This method returns a shared pointer to an `InputQueue` working as a communication interface between the host and the device via its `send(...)` method.

Lastly, all the `createQueue` function calls were replaced with `createOutputQueue` function calls throughout the entire codebase.

The relevant clickup task is available here: https://app.clickup.com/t/86bym8w49

2024-05-27 09:39 UTC, moratom requested changes
Thanks a lot!

Left a few nitpicks, but looks good.

2024-05-27 09:39 UTC, moratom commented on bindings/python/src/pipeline/node/NodeBindings.cpp
> +        .def("createInputQueue", &Node::Input::createInputQueue, py::arg("maxSize") = 16, py::arg("blocking") = true, DOC(dai, Node, Input, createInputQueue));
It would be better to share the defaults with C++ implementation here - you can use a `constexpr` and then use it both in C++ for the default and in Python.

2024-05-27 09:39 UTC, moratom commented on bindings/python/src/pipeline/node/NodeBindings.cpp
> +        .def("createOutputQueue", &Node::Output::createOutputQueue, py::arg("maxSize") = 16, py::arg("blocking") = true, DOC(dai, Node, Output, createOutputQueue))
Let's remove the `createQueue` and same comment for the default as for the InputQueues.

2024-05-27 09:39 UTC, moratom commented on include/depthai/pipeline/Node.hpp
> +        [[deprecated("Use 'createOutputQueue()' instead")]] std::shared_ptr<MessageQueue> createQueue(unsigned int maxSize = 16, bool blocking = true);
Let's just remove it for now, no need to keep the old function as the only people using this used it in an experimental phase

2024-05-27 09:39 UTC, moratom commented on include/depthai/pipeline/Node.hpp
> +
Could we do with a "private/protected" inheritance here to be able to expose only the relevant API (`send`)?

2024-05-27 09:39 UTC, moratom commented on src/pipeline/Node.cpp
> +    sendThreadCv_.notify_all();
Is the extra syncronisation needed here?

Generally speaking the `MessageQueue` already provides a blocking `send` and `get`

2024-05-29 10:23 UTC, themarpe commented on include/depthai/pipeline/Node.hpp
> +
When was the `_` postfix introduced for private members? 
IMO, the private designator + IDE handles this

2024-05-30 14:17 UTC, lnotspotl commented on bindings/python/src/pipeline/node/NodeBindings.cpp
> +        .def("createInputQueue", &Node::Input::createInputQueue, py::arg("maxSize") = 16, py::arg("blocking") = true, DOC(dai, Node, Input, createInputQueue));
Fixed in d89c76e2a5f9c6944ddf53dd35361029ecdd41a5. Not sure about the default values for `maxSize` and `blocking` though.

2024-05-30 14:17 UTC, lnotspotl commented on bindings/python/src/pipeline/node/NodeBindings.cpp
> +        .def("createOutputQueue", &Node::Output::createOutputQueue, py::arg("maxSize") = 16, py::arg("blocking") = true, DOC(dai, Node, Output, createOutputQueue))
Fixed in d89c76e2a5f9c6944ddf53dd35361029ecdd41a5.

2024-05-30 14:21 UTC, lnotspotl commented on include/depthai/pipeline/Node.hpp
> +
I've built the habit of adding the `_` suffix to my private attributes after seeing it in many codebases, though it makes sense not to include them here as it would  be inconsistent with the already existing code. I will keep this in mind in the future.

I've changed the `InputQueue`'s class declaration, exposing only the important method, i.e. `send`. This change is part of b19b0945e08b18ac6ea277f5be17d7081f7023d9

2024-05-30 15:21 UTC, moratom commented on include/depthai/pipeline/Node.hpp
> +
Can we maybe move to a new file, to keep the file sizes more manageable.

Same for the implementation file.

2024-05-30 15:21 UTC, moratom commented on include/depthai/pipeline/Node.hpp
> +    std::unique_ptr<MessageQueue> queuePtr;
Maybe the queue can have just a regular input (similar to all other nodes)?

2024-05-30 15:21 UTC, moratom commented on src/pipeline/Node.cpp
> +}
If the simplification can be done - this would only pass-through the send directly to the input:

```suggestion
void InputQueue::send(const std::shared_ptr<ADatatype>& msg) {
    input->send(msg);
}
```

2024-05-30 15:21 UTC, moratom commented on src/pipeline/Node.cpp
> +}
```suggestion
void InputQueue::run() {
    try {
        while(isRunning()) {
              output.send(input.get())
        }
    } catch(const MessageQueue::QueueException& ex) {
        stopThreadFlag = true;
    } catch(const std::runtime_error& ex) {
        std::cout << "Node threw exception, stopping the node. Exception message: " << ex.what() << std::endl;
    }
}
```

I was thinking if this could be simplified as such?

The `start` `stop` and `wait` functions could then be left at default implementations I believe.

2024-05-30 15:21 UTC, moratom commented on include/depthai/pipeline/Node.hpp
> +    std::unique_ptr<MessageQueue> queuePtr;
Then in the constructor - it could just readjust the queue size in the input.

2024-05-30 18:33 UTC, lnotspotl commented
Thanks a lot, @moratom. Appreciate the feedback. I was reinventing the wheel originally and with your suggestions incorporated into this PR the code is way simpler.

2024-06-03 14:34 UTC, moratom commented on include/depthai/pipeline/InputQueue.hpp
> +    friend class Node::Input;
Can we make the inheritance here protected, so the public API from the node is not exposed to the queue as well>

2024-06-03 14:35 UTC, moratom commented on include/depthai/pipeline/Node.hpp
> +#include <condition_variable>
Not used anymore right?

2024-06-05 15:34 UTC, themarpe approved these changes

2024-06-06 14:05 UTC, merged