Release 2.27.0
luxonis/depthai-core pull request #1045
Opened 2024-06-25 17:20 UTC by moratom

2024-06-25 18:40 UTC, themarpe requested changes

2024-06-25 18:49 UTC, moratom commented on README.md
> +> ℹ️ On Linux distributions based on RPMs, you need to install `perl-core` for us to OpenSSL dependency.
`perl-core` is a build time dependency for openssl, not runtime.

2024-06-25 18:51 UTC, themarpe commented on README.md
> +> ℹ️ On Linux distributions based on RPMs, you need to install `perl-core` for us to OpenSSL dependency.
Ah, got it. Thanks!

Then the suggested change should be:
```suggestion
> ℹ️ On Linux distributions based on RPMs, you need to install `perl-core` required by OpenSSL dependency.
```

2024-06-25 18:51 UTC, themarpe commented on src/utility/sha1.hpp
> +/*
Perhaps add a note for now, in the future we might be able to swap if needed

2024-06-25 18:52 UTC, moratom commented on src/utility/sha1.hpp
> +/*
On Windows, we don't use the OpenSSL but use `SCHANNEL` instead - so we don't have the `sha1` from there.

We could `ifdef` it to get it from the `SCHANNEL` that's used on Windows, but I figured it's easier to bring it in and have a single implementation.

2024-06-25 21:48 UTC, moratom commented on src/utility/sha1.hpp
> +/*
Added a comment that we can use SChannel and OpenSSL instead.

2024-06-26 14:19 UTC, themarpe approved these changes

2024-06-26 14:20 UTC, merged