Python type mismatch
luxonis/depthai-core pull request #1082
Opened 2024-07-31 13:29 UTC by borbrudar

Added an extra argument to `addTensor` to allow users to specify the underlying tensor data type.

2024-07-31 15:29 UTC, moratom reviewed
I think this will still behave a bit unexpected due to how C++ API works.

The int version I believe gets collapsed to uint8_t for example.
 
Let's add tests (see nndata_tensor_test.py).
To catch all various edge cases.

2024-07-31 16:11 UTC, borbrudar commented
True, but that's due to the internals of how `addTensor` works, specifically:

``` // Convert data to u8 or fp16 and write to data
        if(std::is_integral<_Ty>::value) {
            for(uint32_t i = 0; i < tensor.size(); i++) {
                vecData->data()[i + offset] = (uint8_t)tensor.data()[i];
            }
        } else {
            for(uint32_t i = 0; i < tensor.size(); i++) {
                *(uint16_t*)(&vecData->data()[2 * i + offset]) = fp32_to_fp16(tensor.data()[i]);
            }
        }

Tests from `nndata_tensor_test.py` seem to pass with the modified signatures, although the optional parameter doesn't appear to be optional.

2024-09-16 15:28 UTC, moratom requested changes
Let's remove all of the specialized functions and rather have it as such:
* By default we try to infer the type from the tensor
* We allow to override the type with a function argument

We can do so both in C++ and Python I believe.

And please add tests as well.

2024-09-16 15:28 UTC, moratom commented on include/depthai/pipeline/datatype/NNData.hpp
> +        else if(dataType == dai::TensorInfo::DataType::FP32 || dataType == dai::TensorInfo::DataType::INT) sConvertedData *= 4;
Let's do a switch here and cover all cases, so we visually see that nothing is missing

2024-09-16 16:04 UTC, borbrudar commented on include/depthai/pipeline/datatype/NNData.hpp
> +        else if(dataType == dai::TensorInfo::DataType::FP32 || dataType == dai::TensorInfo::DataType::INT) sConvertedData *= 4;
amended

2024-09-17 14:32 UTC, borbrudar commented
Reworked, however there are limitations to type conversions from python to c++ and vice versa, e.g. fp16 is not supported in pybind, so we have to cast it to a different type before we can pass it to c++ (i've chosen to upcast it to fp32). Similarly fp64 is not supported in c++ so i downcast it to fp32.

2024-09-19 12:24 UTC, moratom requested changes

2024-09-19 12:24 UTC, moratom commented on include/depthai/pipeline/datatype/NNData.hpp
> +//#endif
Intentional?

2024-09-19 12:24 UTC, moratom commented on include/depthai/pipeline/datatype/NNData.hpp
> +//#ifdef DEPTHAI_XTENSOR_SUPPORT
I think this is still needed?

2024-09-19 12:24 UTC, moratom commented on include/depthai/pipeline/datatype/NNData.hpp
>      };
Let's add tests for these too

2024-09-19 14:10 UTC, borbrudar commented on include/depthai/pipeline/datatype/NNData.hpp
> +//#endif
;)

2024-09-19 17:21 UTC, borbrudar commented on include/depthai/pipeline/datatype/NNData.hpp
>      };
Added.

2024-09-25 15:30 UTC, merged