Synchronize cpp examples with python
luxonis/depthai-core pull request #110
Opened 2021-04-14 15:54 UTC by csaba-luxonis

This PR is WIP, will be updated once it's ready to review.

2021-04-15 02:06 UTC, Luxonis-Brandon commented
Thanks for making these.  These will be great to have!  Will be so nice to have full Python and C++ examples for folks.

2021-04-15 02:07 UTC, Luxonis-Brandon commented
Oh and once these are done @csaba-luxonis - we should do the switcher on our docs so folks can switch between the Python code sample and the C++ code sample on the same page.

2021-04-15 12:05 UTC, csaba-luxonis commented
Yeah, that would be amazing.

2021-04-15 12:43 UTC, themarpe commented
I think we should do this in other direction:
Remove example numbers from python examples and leave these here as is.

Documentation should mark examples (code samples) with numbers but just as an easier overview

2021-04-15 14:20 UTC, Luxonis-Brandon commented
Oh, yes.  Sorry I didn't meant to say that we should have the numbers on these.  I agree we should remove the numbers from the Python examples.  And just have the documentation designate the order of the code samples.

2021-04-15 20:22 UTC, themarpe requested changes

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +#include "utility.hpp"
Unneeded

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +    // Keyboard interrupt (Ctrl + C) detected
Remove leading whitespace

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +        videoFile.write((char*)h264Packet->getData().data(), h264Packet->getData().size());
```
videoFile.write(static_cast<char*>(h264Packet->getData().data()), h264Packet->getData().size());
```

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +    videoFile.close();
Unneeded - RAII should take care of it

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +    auto videoFile = std::fstream(h265Path, std::ios::out | std::ios::binary);
```
auto videoFile = std::ofstream(h265Path, std::ios::binary);
```

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +static bool alive = true;
```
static std::atomic<bool> alive{true};
```

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +    signal(SIGINT, &sigintHandler);
Maybe a small comment on this + remove the using std and std::chrono, we don't use it here actually
```
std::signal(SIGINT, &sigintHandler);
```

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +// Inludes common necessary includes for development using depthai library
Typo: `Inludes` -> `Includes`

2021-04-15 20:22 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +
Extra line

2021-04-19 10:15 UTC, csaba-luxonis commented on examples/src/04_rgb_encoding.cpp
> +        videoFile.write((char*)h264Packet->getData().data(), h264Packet->getData().size());
static_cast from 'unsigned char *' to 'char *' is not allowed

2021-04-20 18:25 UTC, themarpe commented on examples/src/04_rgb_encoding.cpp
> +        videoFile.write((char*)h264Packet->getData().data(), h264Packet->getData().size());
Good catch, `reinterpret_cast<char*>` should do

I guess we can leave C-style cast in this case

2021-04-20 18:29 UTC, themarpe commented
Also one thing I was thinking, if we allow passing the output file as parameter (as well as the default), to be able to set it to `/dev/null` / `nul` for testing case. (Same applies to Python side)

2021-04-29 11:11 UTC, themarpe requested changes
Throughout examples: use ImgFrame::Type alias instead of Raw*
```
manip->initialConfig.setFrameType(dai::ImgFrame::Type::BGR888p);
```

2021-05-11 13:00 UTC, themarpe submitted a review, later dismissed
LGTM apart from:

Style - either same line or with curly braces (in a couple of cases)
```
if(syncNN) {
    ...
} else {
    ...
}
```

2021-05-19 12:42 UTC, szabi-luxonis approved these changes
LGTM

2021-05-19 14:31 UTC, merged