V3 Events & Snaps
luxonis/depthai-core pull request #1150
Opened 2024-10-14 06:31 UTC by Serafadam

2024-10-25 09:41 UTC, Serafadam commented on examples/cpp/HostNodes/events.cpp
> +    eventsManager->setUrl("https://events-ingest.apps.stg.hubcloud");
The default URL is for production but AFAIK snaps & events are not available there yet, so for now we need to use this URL

2024-10-25 09:42 UTC, Serafadam commented on include/depthai/utility/EventsManager.hpp
> +                  const std::string& deviceSerialNo = "");
Error as in `bool`? Or custom error code?

2024-11-04 11:36 UTC, moratom commented on include/depthai/utility/EventsManager.hpp
> +                  const std::string& deviceSerialNo = "");
We can do bool I think.

2024-11-04 11:36 UTC, moratom commented on include/depthai/utility/EventsManager.hpp
> +                  const std::string& deviceSerialNo = "");
And keep the logger::error, now there's no feedback if the function is not successful, if one is not looking into the terminal output.

2024-12-03 16:10 UTC, moratom requested changes
Let's make the event manager enable-able with it's own flag and just code in the logic that protobuf is required for it and test that the code can be compiled without it, otherwise LGTM

2024-12-03 16:10 UTC, moratom commented on examples/cpp/HostNodes/events.cpp
> +    eventsManager->setUrl("https://events-ingest.apps.stg.hubcloud");
I think this is now available right?

2024-12-03 16:10 UTC, moratom commented on recording.mp4
Force push out of the history

2024-12-03 16:10 UTC, moratom commented on bindings/python/src/utility/EventsManagerBindings.cpp
This likely doesn't compile when protobuf support is disabled right?

2024-12-06 14:03 UTC, moratom approved these changes

2024-12-06 14:23 UTC, merged