Clarified README
luxonis/depthai-core pull request #125
Opened 2021-04-30 23:47 UTC by themarpe

Added more information on integration into both CMake and non-CMake based projects.
Also modified CMake commands to be compatible down to version 3.5 (Default on Ubuntu16.04) to ease first time usage.

2021-05-01 00:04 UTC, szabi-luxonis requested changes

2021-05-01 00:04 UTC, szabi-luxonis commented on README.md
> +1. Then install: [Installing](##installing)
Change to 1,2,3,4

2021-05-01 00:18 UTC, themarpe commented on README.md
> +1. Then install: [Installing](##installing)
Markdown automatically iterates them.
Might still look better in raw form though - can modify back.

2021-05-01 00:43 UTC, szabi-luxonis approved these changes

2021-05-03 00:26 UTC, themarpe commented
CC: @alex-luxonis @szabi-luxonis with additional fixes (edited OP)

2021-05-03 11:02 UTC, szabi-luxonis approved these changes

2021-05-03 13:08 UTC, merged