stereo node getMaxDisparity()
luxonis/depthai-core pull request #132
Opened 2021-05-11 22:59 UTC by Erol444

added a function in stereo node that returns the maxDisparity. Also changed stereo_example.cpp to use this new function

2021-05-11 23:44 UTC, themarpe requested changes
Also run clangformat (style check is failing):
`cmake --build build/ --target clangformat`

2021-05-12 00:34 UTC, alex-luxonis commented on include/depthai/pipeline/node/StereoDepth.hpp
> +    float getMaxDisparity();
Any specific need for `float` instead of `int`?

And on the return description, the number of disparity levels would be `+1` more (also disparity value 0).

2021-05-12 18:43 UTC, Erol444 commented on include/depthai/pipeline/node/StereoDepth.hpp
> +    float getMaxDisparity();
So when you use it in code it doesn't matter if it's `255.0` or `255`. Great, thanks for noticing that:)

2021-05-14 13:24 UTC, themarpe approved these changes

2021-05-14 13:54 UTC, merged