Separate Queue handling from core API
luxonis/depthai-core pull request #150
Opened 2021-06-08 03:42 UTC by kunaltyagi

2021-06-08 12:26 UTC, kunaltyagi commented on src/device/Device.cpp
> +    // Is this expected? Should we clear the queues before closing the device?
Question 1

2021-06-08 12:26 UTC, kunaltyagi commented on src/device/Device.cpp
> +    // Open queues upfront, let queues know about data sizes (input queues)
Question 2: this comment is no longer valid. Is the code still valid though?

Doing what the comment says requires breaking the startPipeline into 2 parts: pre and post (setupComm and startPipeline for example)

2021-06-08 13:28 UTC, themarpe requested changes
A couple of things are needed in this case:
 - `getConnection` to get the underlying `XLinkConnection` if working with streams manually is desired.
 - StreamPacketParser will have to be exposed & preferably cleaned up a bit (otherwise manual handling isn't possible)
 - I'd move DeviceBase to its own .hpp & .cpp

2021-06-08 13:28 UTC, themarpe commented on src/device/Device.cpp
> +    // Open queues upfront, let queues know about data sizes (input queues)
What if we just move `DeviceBase::startPipeline(pipeline)` after opening the queues?

2021-06-08 13:28 UTC, themarpe commented on src/device/Device.cpp
> +    // Is this expected? Should we clear the queues before closing the device?
The connection is closed beforehand as queues block on waiting for data coming to XLink streams. 
This is a limitation of XLink as these blocking functions cannot be terminated gracefully.

2021-06-08 14:05 UTC, kunaltyagi reviewed
1. I made connection protected. I assume you'd prefer instead to add a function?
2. Would it be as simple as exposing the header properly (and relevant CMake changes)?
3. Sure. Will do that soon

2021-06-08 14:05 UTC, kunaltyagi commented on src/device/Device.cpp
> +    // Is this expected? Should we clear the queues before closing the device?
Again, the issue is that `close` has multiple steps, and the queue handling is interleaved with the actual XLink setup logic. Any ideas on cleaning up this code? You'd be a better judge than me.

2021-06-08 14:25 UTC, themarpe commented on src/device/Device.cpp
> +    // Open queues upfront, let queues know about data sizes (input queues)
We could do the same check twice, but I agree, lets move the check:
```
checkClosed();

    // first check if pipeline is not already running
    if(isPipelineRunning()) {
        throw std::runtime_error("Pipeline is already running");
    }
```
outside and create a private function for "starting" the pipeline (`startPipelineImpl` or something like that), which doesn't check.
Then we can check if pipeline is running, then create queues and at the end `startPipelineImpl`

For base we do just check and `startPipelineImpl`

2021-06-08 14:30 UTC, themarpe commented on src/device/Device.cpp
> +    // Is this expected? Should we clear the queues before closing the device?
Ohh, yeah, clearing them in the end should suffice. 
So callbacks must be removed first, device connection closed and then the queues can be cleared.

As is right now looks good to me on first glance

2021-06-08 14:35 UTC, themarpe commented
> 1. I made connection protected. I assume you'd prefer instead to add a function?

The connection being protected is great, but we also need to expose it as part of public API alongside being protected for internal use. 
Otherwise not much can be done with device without having its underlying XLinkConnection object. (The connection is needed for opening XLinkStreams)

> 2. Would it be as simple as exposing the header properly (and relevant CMake changes)?

Yes. And one extra thing that will have to be done eitherway are bindings, but we'll think about that after this PR is finalized.

> 3. Sure. Will do that soon

Thanks!

2021-06-08 15:22 UTC, Luxonis-Brandon commented
And CC: @saching13 on all the above.  Really cool.  Thanks, both!

2021-06-08 23:38 UTC, kunaltyagi commented
No modifications to startPipeline yet

2021-06-09 04:39 UTC, kunaltyagi commented on src/device/Device.cpp
> +    // Open queues upfront, let queues know about data sizes (input queues)
I've added another check in derived class. Is this also sufficient? I removed the extra `checkClosed` (since it's already part of `isPipelineRunning`)

2021-06-11 09:14 UTC, themarpe requested changes

2021-06-11 09:14 UTC, themarpe commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
>  // StreamPacket structure ->  || imgframepixels... , serialized_object, object_type, serialized_object_size ||
This file being exposed now needs a tad more love:
 - class StreamPacketParser with static methods
 - serializeData -> serializeMessage
 - serializeMessage 4 overloads (shared_ptr and reference to RawBuffer & ADatatype)
 ```
std::vector<std::uint8_t> serializeMessage(const std::shared_ptr<RawBuffer>& rawMsg);
std::vector<std::uint8_t> serializeMessage(const RawBuffer& rawMsg);
std::vector<std::uint8_t> serializeMessage(const std::shared_ptr<ADatatype>& msg);
std::vector<std::uint8_t> serializeMessage(const ADatatype& msg);
```

For reference check `DataInputQueue::send` functions

2021-06-12 04:00 UTC, kunaltyagi commented on include/depthai/device/DeviceBase.hpp
> +    std::shared_ptr<XLinkConnection> connection;
What's the benefit given that `getConnection` has been added? Brewity?

2021-06-12 04:07 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
>  // StreamPacket structure ->  || imgframepixels... , serialized_object, object_type, serialized_object_size ||
Should the API be `const std::shared_ptr<const T>& m` since there are `const T& m` overloads?

2021-06-12 04:26 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
>  // StreamPacket structure ->  || imgframepixels... , serialized_object, object_type, serialized_object_size ||
PS: RawBuffer::serialize is not const. Should it be made const?

2021-06-12 04:41 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
>  // StreamPacket structure ->  || imgframepixels... , serialized_object, object_type, serialized_object_size ||
Compilation error expected since waiting on ^^^ PR

2021-06-14 01:58 UTC, kunaltyagi commented on src/device/Device.cpp
> +    return DeviceBase::startPipeline(pipeline);
My mistake. Fixed it.

2021-06-26 03:06 UTC, kunaltyagi commented
PTAl @themarpe

2021-06-28 14:13 UTC, themarpe commented on include/depthai/device/DeviceBase.hpp
> +    std::shared_ptr<XLinkConnection> connection;
The derived class `Device` (and others potentially) can use it as is, as it is the main thing that derived classes will need access to (especially with the need to change it, etc..).

2021-06-28 14:15 UTC, themarpe commented on src/device/Device.cpp
> +    const auto& connection = getConnection();
Also taking a const reference to a returned temporary object, not sure if this is valid

2021-06-28 14:21 UTC, themarpe commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
>  // StreamPacket structure ->  || imgframepixels... , serialized_object, object_type, serialized_object_size ||
> Should the API be const std::shared_ptr<const T>& m since there are const T& m overloads?
By `const T` do you mean a template? It could be as we wouldn't be exposing any "private" dependencies, although in its current form I think its okay as is - moves the actual implementation to the .cpp

2021-06-28 14:25 UTC, themarpe requested changes
Also added some additional responses to the comments.

Otherwise looking good, will give it a test locally after these finishing touches.

Thanks for your contribution!

2021-06-28 14:25 UTC, themarpe commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
> +    static std::shared_ptr<ADatatype> parsePacketToADatatype(streamPacketDesc_t* packet);
Thoughts on naming these `parseMessage` and `parseRawMessage` instead?
Would go better with the corresponding `serializeMessage` functions.

2021-06-28 14:29 UTC, themarpe requested changes

2021-06-28 14:29 UTC, themarpe commented on src/device/Device.cpp
> +    // Close the device before clearning the queues
Typo: clearning -> clearing

2021-06-28 14:45 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
> +    static std::shared_ptr<ADatatype> parsePacketToADatatype(streamPacketDesc_t* packet);
Sure, no issues

2021-06-29 06:57 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/StreamPacketParser.hpp
> +    static std::shared_ptr<ADatatype> parsePacketToADatatype(streamPacketDesc_t* packet);
It's streamPacketParser, so I'm making it streamMessageParser

2021-06-29 08:17 UTC, themarpe commented on include/depthai/pipeline/datatype/ADatatype.hpp
> +    friend class StreamPacketParser;
`friend class StreamMessageParser;`

2021-06-29 10:19 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/ADatatype.hpp
> +    friend class StreamPacketParser;
```suggestion
    friend class StreamMessageParser;
```

2021-07-06 07:17 UTC, kunaltyagi commented
@themarpe PTAL

2021-07-14 10:17 UTC, themarpe requested changes
Started merging but stumbled upon:
```
./depthai-core/examples/rgb_preview 
Connected cameras: 0 RGB 1 LEFT 2 RIGHT 
Usb speed: SUPER
terminate called after throwing an instance of 'std::runtime_error'
  what():  Queue for stream name 'rgb' doesn't exist
Aborted (core dumped)
```

Same with your branch unchanged. Please fix beforehand and merge in / rebase to latest develop

2021-07-14 10:17 UTC, themarpe commented on include/depthai/pipeline/datatype/NNData.hpp
> +    std::shared_ptr<RawBuffer> serialize() const override;
I presume this was meant to be done for all or none of the messages?

2021-07-16 05:12 UTC, kunaltyagi commented
Working on a rebase

2021-07-19 09:23 UTC, kunaltyagi commented on include/depthai/pipeline/datatype/NNData.hpp
> +    std::shared_ptr<RawBuffer> serialize() const override;
Other messages already had them. Just this one didn't have that

2021-07-19 09:33 UTC, kunaltyagi commented
PTAL. Due to huge amounts of code movement, please check the behavior a bit more carefully. Let's get this merged because dealing with merge conflicts is a big pain (due to code being moved across files)

2021-07-19 13:23 UTC, kunaltyagi commented
@themarpe

2021-07-20 09:53 UTC, themarpe commented
@kunaltyagi 
Hopefully I checked out the correct latest of your changes - but I'm still getting the error on simple `rgb_preview` example.
Please fix this beforehand and run the tests locally to verify (preferably with `TEST_TIMEOUT=10 make test`). In CMake configuration specify both `-D DEPTHAI_BUILD_EXAMPLES=ON` and `-D DEPTHAI_BUILD_TESTS=ON`, build and then test with previously mentioned command

2021-07-27 10:04 UTC, kunaltyagi commented
I don't actually know how to reslve the errors...

It's getting harder to rebase and compare. I think I'll start over if you can help fast-track the new PR before other code is merged in Device cpp and hpp files. It'd be easier to start over, but not something I'd do again and again
cc: @Luxonis-Brandon

2021-07-27 12:41 UTC, themarpe commented
@kunaltyagi I presume the error happens because Device doesn't open the queues upfront (the underlying startPipeline doesnt seem to do the right thing in Device case)

You can either fix in your branch, and I'll handle the merging with latest, or better if you fix after merging to latest in your own branch, to not reintroduce any issues.

By helping to fast track, what did you have in mind? I guess if you give me access to your branch I can help merging in latest develop and resolving conflicts?

2021-07-28 05:29 UTC, kunaltyagi commented
I already have allowed edits by maintainers
![image](https://user-images.githubusercontent.com/2657068/127268696-4ce33ec2-4655-4d0b-ac2a-3eadfbba0d81.png)

> error happens because Device doesn't open the queues upfront 

I see. Let me take a look at see how I can re-shuffle the code

2021-07-28 05:33 UTC, kunaltyagi commented on src/device/Device.cpp
> +    const auto& connection = getConnection();
Taking a const reference to temporary extends the lifetime.

See the example in rvalue reference here: http://en.cppreference.com/w/cpp/language/reference

2021-07-28 05:38 UTC, kunaltyagi commented on src/device/DeviceBase.cpp
> +    }
These are the only lines which have been inverted in startPipeline logic. Queues are being opened upfront otherwise.

Current flow:
startPipeline -> Device::startPipelineImpl -> DeviceBase::startPipelineImpl

2021-07-28 18:03 UTC, themarpe commented on src/device/Device.cpp
> +    const auto& connection = getConnection();
Thanks for the link - didn't know:)

Still, preferably expose using:

> Can be removed after DeviceBase::connection is protected

2021-07-28 18:58 UTC, themarpe commented on src/device/DeviceBase.cpp
> +    }
@kunaltyagi it seems that using this:
This is the stack trace:
```
dai::DeviceBase::startPipelineImpl(dai::Pipeline const&) (src/device/DeviceBase.cpp:815)
dai::DeviceBase::startPipeline(dai::Pipeline const&) (src/device/DeviceBase.cpp:811)
dai::DeviceBase::init2(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tl::optional<dai::Pipeline const&>) (src/device/DeviceBase.cpp:638)
dai::DeviceBase::init(dai::Pipeline const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (src/device/DeviceBase.cpp:388)
dai::DeviceBase::DeviceBase(dai::Pipeline const&) (src/device/DeviceBase.cpp:233)
dai::Device::Device(dai::Pipeline const&) (include/depthai/device/Device.hpp:26)
main (examples/src/rgb_preview.cpp:28)
__libc_start_main (@__libc_start_main:60)
_start (@_start:14)
```

With added constructor in Device.

I think the following happens: https://stackoverflow.com/a/962148

2021-07-29 00:50 UTC, kunaltyagi commented
Tested and worked.

I needed to add the following to CMakeLists.txt for examples and tests to get it working:
```cmake
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lrt")
```

Any ideas why? Should I create a PR for the same?

2021-07-29 01:51 UTC, kunaltyagi commented
> Any ideas why? Should I create a PR for the same?

Apparently, adding it to the depthai-core library also does the trick. If it's ok, I can create a PR for the same. (1 line: `target_link_options(${TARGET_CORE_NAME} INTERFACE "-lrt")`)

2021-07-29 13:34 UTC, themarpe commented
@kunaltyagi 
2. things:
 - DeviceBase constructors taking a pipeline don't start it now. I think a call to startPipeline should remain there, which will call `DeviceBase::startPipeline` (or can be explicit `DeviceBase::startPipeline` in ctor, just for it to be clear)
 - The now overloaded Device ctor needs a try catch around and do a close otherwise ctor will fail but device won't gracefully close.
 
Regarding the `rt` library - never happend yet on any system:/ Can you test if that is required in latest `develop` as well and if so can you share your system details?
I presume that if this might be related to "Threading" library that CMake knows to apply underneath, the correct place would be setting it in XLink as public: https://github.com/luxonis/XLink/blob/master/CMakeLists.txt#L24-L27

Would have to check which codebase actually pulls in the requirement for `rt`.

Otherwise this should be applied to Linux only afaik so should have a check with it and no need to do a flag, can just be:
```
target_link_libraries(target PUBLIC rt)
```

2021-07-29 14:46 UTC, kunaltyagi commented
I added a close for the second point.

What is the actionable item for the first point? There's no need for DeviceBase to call `startPipeline`, right?

The `Device` class takes care of that from the user perspective, and the developers of derived classes of `DeviceBase` can device what kind of behavior is preferred for them.

2021-07-30 00:57 UTC, themarpe commented
I think it just mixes with current constructors - these constructors actually shouldn't call DeviceBase(pipeline, ...) but regular non pipeline starting constructors. 

In Device constructors, there are 2 major ones - Device(pipeline, ...) and Device(openvino, ...).
The first one always starts the pipeline by itself and no subsequent `startPipeline` is required (or possible), while the second doesn't start a pipeline but just boots the correct FW (specified by openvino) and then waits for any other RPC calls to be made and/or pipeline started.

If we make DeviceBase not handle queues automatically, but still expose same API for constructors, IMO same logic should apply. So DeviceBase(pipeline, ...) starts the pipeline by itself, while DeviceBase(openvino, ...) doesn't.

2021-07-30 01:15 UTC, kunaltyagi commented
Thoughts on removing the `DeviceBase(pipeline)` ctors?
* DeviceBase doesn't have enough information to start pipeline safely (due to your arguments combined with the virtual function issue)
* This can be a feature for the `Device` class solely: start pipeline because it can handle queues

2021-07-30 09:09 UTC, themarpe commented
The second option is compelling, although for the first one it can indeed start the pipeline normally - its just going to call it's own DeviceBase::startPipelineImpl, resulting in started pipeline without queues opened upfront.

Maybe best to just modify the current Device ctors to call `Device(pipeline,...) : DeviceBase(pipeline.getOpenVINOVersion(), ...) {}`
And for DeviceBase adding back the call but explicitly to its own impl.

2021-07-30 14:50 UTC, kunaltyagi commented
> its just going to call it's own DeviceBase::startPipelineImpl, resulting in started pipeline without queues opened upfront.

I agree with the second portion: `Device(pipeline)` forwards to `Devicebase(openVinoVersion)`, and I still feel that adding `DeviceBase(pipeline)` creates a more confusing (and faulty: `starting pipeline without queues opened upfront`) API

2021-07-30 15:17 UTC, themarpe commented
> and I still feel that adding DeviceBase(pipeline) creates a more confusing (and faulty: starting pipeline without queues opened upfront) API

This actually won't happen - when a users uses DeviceBase constructor, they create a DeviceBase object, on which they won't be able to call `getOutputQueue`. I'd still rather retain the mostly the same behavior between DeviceBase and Device with exception of queues (at least in current of debate context and path of the PR)

2021-07-30 16:43 UTC, kunaltyagi commented
How does this look?

2021-07-30 17:00 UTC, themarpe commented
@kunaltyagi Thanks, looking good.
Will clone locally and update with latest and merge. Most likely tomorrowish.

2021-08-02 15:24 UTC, kunaltyagi commented
Just a ping :)

2021-08-03 16:42 UTC, themarpe commented
@kunaltyagi updated with latest develop. Hopefully haven't missed anything. Also created a branch on depthai-python with bindings, but have to add StreamMessageParser to it as well.

I'm still observing issues running the examples/tests. Specifically the `image_manip_node_test`. AFAIK `close` is suffering from same issues as opening the pipeline did. Its called from destructor where after `Device` is destructed, `DeviceBase` doesn't call its `Device::closeImpl` but just its own. (Construction/destruction: `DeviceBase->Device ... Device->DeviceBase` <- issue)

2021-08-03 17:11 UTC, kunaltyagi commented
FYI: The windows CI failed before I pushed

I modified the dtor in a similar fashion and added a note for developers. The test runs without any issue now.

2021-08-03 17:53 UTC, kunaltyagi commented
Errors on Windows CI:
```
D:\a\depthai-core\depthai-core\tests\src\image_manip_node_test.cpp(43,40): error C2668: 'dai::Device::Device': ambiguous call to overloaded function [D:\a\depthai-core\depthai-core\build\tests\image_manip_node_test.vcxproj]
D:\a\depthai-core\depthai-core\tests\src\color_camera_node_test.cpp(41,40): error C2668: 'dai::Device::Device': ambiguous call to overloaded function [D:\a\depthai-core\depthai-core\build\tests\color_camera_node_test.vcxproj]
D:\a\depthai-core\depthai-core\include\depthai\device/Device.hpp(59,5): message : could be 'dai::Device::Device(const dai::Pipeline &,const dai::DeviceInfo &,bool)' [D:\a\depthai-core\depthai-core\build\tests\image_manip_node_test.vcxproj]
D:\a\depthai-core\depthai-core\include\depthai\device/Device.hpp(59,5): message : could be 'dai::Device::Device(const dai::Pipeline &,const dai::DeviceInfo &,bool)' [D:\a\depthai-core\depthai-core\build\tests\color_camera_node_test.vcxproj]
D:\a\depthai-core\depthai-core\tests\src\image_manip_node_test.cpp(43,40): message : while trying to match the argument list '(dai::Pipeline, dai::DeviceInfo)' [D:\a\depthai-core\depthai-core\build\tests\image_manip_node_test.vcxproj]
D:\a\depthai-core\depthai-core\tests\src\color_camera_node_test.cpp(41,40): message : while trying to match the argument list '(dai::Pipeline, dai::DeviceInfo)' [D:\a\depthai-core\depthai-core\build\tests\color_camera_node_test.vcxproj]
D:\a\depthai-core\depthai-core\tests\src\image_manip_node_test.cpp(43,40): message : note: qualification adjustment (const/volatile) may be causing the ambiguity [D:\a\depthai-core\depthai-core\build\tests\image_manip_node_test.vcxproj]
D:\a\depthai-core\depthai-core\tests\src\color_camera_node_test.cpp(41,40): message : note: qualification adjustment (const/volatile) may be causing the ambiguity [D:\a\depthai-core\depthai-core\build\tests\color_camera_node_test.vcxproj]
```

Missing default ctor in `Device` (definitely missing, required for calibration examples)

2021-08-05 14:32 UTC, themarpe commented
Seems to work now as expected - MSVC was nitpicking, removed default arguments.
Will be merging after a release.

2021-08-05 15:56 UTC, kunaltyagi commented
The default ctor errors have remained

2021-08-06 12:19 UTC, kunaltyagi commented
🎊 yay 🎉

2021-08-09 02:21 UTC, kunaltyagi commented
@themarpe Will this be included in the next release?

2021-08-10 14:07 UTC, themarpe commented
@kunaltyagi yes, I plan to do so.
Currently working on some bootloader changes, but after I move back to core, will merge this in. 
Might come to develop by the end of this week

2021-08-12 16:43 UTC, merged