Fixed Seg Fault in getImuToCameraExtrinsics
luxonis/depthai-core pull request #156
Opened 2021-06-11 16:42 UTC by saching13

2021-06-11 16:50 UTC, themarpe requested changes
I presume segfault happened becasue of line 347, accessing tranformationMatrix which is empty?

If thats the case, please place a check there as well, could be empty in different cases. 

Same applies to other places

2021-06-11 16:50 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +        throw std::runtime_error("IMU calibration data is not available on device yet!!!");
`IMU calibration data is not available on device yet.`

2021-06-11 16:59 UTC, saching13 commented
> I presume segfault happened becasue of line 347, accessing tranformationMatrix which is empty?
> 
> If thats the case, please place a check there as well, could be empty in different cases.
> 
> Same applies to other places

`std::vector<std::vector<float>> transformationMatrix = eepromData.imuExtrinsics.rotationMatrix;`
The transformation matrix is a copy of the rotation matrix. So it will be empty only when rotation matrix is empty. And rotation matrix will be either empty or have 3x3 always.

2021-06-12 07:36 UTC, themarpe requested changes

2021-06-12 07:36 UTC, themarpe commented on src/device/CalibrationHandler.cpp
>      std::vector<std::vector<float>> transformationMatrix = eepromData.imuExtrinsics.rotationMatrix;
Is this line guarenteed to not be empty? No check required? If it can be then vector should be resized first

2021-06-12 07:44 UTC, saching13 commented on src/device/CalibrationHandler.cpp
>      std::vector<std::vector<float>> transformationMatrix = eepromData.imuExtrinsics.rotationMatrix;
` if(eepromData.imuExtrinsics.rotationMatrix.size() == 0 || eepromData.imuExtrinsics.toCameraSocket == CameraBoardSocket::AUTO) {       
 throw std::runtime_error("IMU calibration data is not available on device yet.");   
 }`

Since this above section throws an error  when `eepromData.imuExtrinsics.rotationMatrix.size()` is zero the code never reaches the part where it is assigned to the `transformationMatrix`. So I thought we don't need to add an another check for that. 
Is there something I am missing or not taking into consideration ?

2021-06-13 08:23 UTC, themarpe approved these changes

2021-06-13 08:23 UTC, themarpe commented on src/device/CalibrationHandler.cpp
>      std::vector<std::vector<float>> transformationMatrix = eepromData.imuExtrinsics.rotationMatrix;
Misread the first check, all good in this case (just recheck other functions if similar situation could occur)

2021-06-16 19:49 UTC, merged