ImgFrame: report camera settings (focus, exposure, iso)
luxonis/depthai-core pull request #191
Opened 2021-08-04 17:13 UTC by alex-luxonis

Add new API which can be used on `ImgFrame` packets received from camera:
- getExposureTime()
- getSensitivity()
- getLensPosition() - (note: lens position may be reported one frame in advance at the moment)

FW updates:
- fix black image when initial manual exposure was set with other controls
- fix switching from auto to manual exposure causing the lens to jump to zero 
  (note: the lens is directly set now with manual focus, bypassing 3A)
  
WIP, currently only reports values for ColorCamera.

Related PR: https://github.com/luxonis/depthai-shared/pull/51

2021-08-06 21:53 UTC, themarpe requested changes

2021-08-06 21:53 UTC, themarpe commented on src/pipeline/datatype/ImgFrame.cpp
> +}
IMO duration would be more applicable in this case
```
std::chrono::microseconds ImgFrame::getExposureTime() const {
    return std::chrono::microseconds(img.cam.exposureTimeUs);
}
```

2021-11-11 11:41 UTC, themarpe requested changes
Seems like `video` frames don't get this information applied to it, but `preview` do. 
TODO - check how FW handles this.

2022-09-21 13:29 UTC, Erol444 commented
This (newer) PR also includes features added in this PR: https://github.com/luxonis/depthai-core/pull/210

2022-09-27 19:57 UTC, alex-luxonis commented
> Seems like `video` frames don't get this information applied to it, but `preview` do.
`VideoEncoder` didn't forward the new ImgFrame metadata, was fixed.

2022-10-03 12:51 UTC, merged