Update README.md instructions with OpenCV troubleshooting
luxonis/depthai-core pull request #195
Opened 2021-08-11 13:25 UTC by VanDavv

While I was building the core examples, I stumbled upon an issue with a missing OpenCV installation. This PR adds small README.md updates that should help others having this issue

2021-08-11 14:02 UTC, szabi-luxonis requested changes

2021-08-11 14:02 UTC, szabi-luxonis commented on README.md
> +Then navigate to `build/examples` folder and run a preffered test
preferred example

2021-08-11 14:02 UTC, szabi-luxonis commented on README.md
> +cd build
cd build/examples

2021-08-11 14:02 UTC, szabi-luxonis commented on README.md
> +ctest
./{example_name}

running tests were described in previous paragraph

2021-08-11 14:20 UTC, szabi-luxonis approved these changes

2021-08-11 20:17 UTC, themarpe requested changes

2021-08-11 20:17 UTC, themarpe commented on README.md
> +./rgb_mobilenet
Multi config generators (like Visual Studio on Windows) will have these in eg: `build/examples/[Debug/Release/...]/rgb_mobilenet`
Might be worth pointing this out

2021-08-11 20:17 UTC, themarpe commented on README.md
> +export OpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4
Probably preferred to add this to `cmake` command when configuring with:
```
cmake -H. -Bbuild -D OpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4
```

To keep this settings "local"

2021-08-11 20:17 UTC, themarpe commented on README.md
> +run this command (replacing default Ubuntu path `` with yours)
> run this command (replacing default Ubuntu path `` with yours)

Dual backticks there a typo?

2021-08-12 12:40 UTC, themarpe requested changes

2021-08-12 12:40 UTC, themarpe commented on README.md
> +Please be aware that multi config generators (like Visual Studio on Windows) will have the examples built in `build/examples/Debug/Release/.../rgb_mobilenet`
Please be aware that multi config generators (like Visual Studio on Windows) will have the examples built in `build/examples/[Debug/Release/...]/rgb_mobilenet`

2021-08-17 19:19 UTC, themarpe approved these changes

2021-08-18 09:41 UTC, merged