Throw XLink specific errors for read/write errors
luxonis/depthai-core pull request #198
Opened 2021-08-16 13:29 UTC by kunaltyagi

2021-08-16 13:30 UTC, kunaltyagi commented
Created from main. Develop seems to be behind main

2021-08-16 13:45 UTC, szabi-luxonis requested changes
LGTM, but need to add python bindings too in `depthai-python`

2021-08-16 14:43 UTC, kunaltyagi commented
Windows CI failing for some reason. Python bindings are added post merge in core, right?

2021-08-16 15:10 UTC, themarpe requested changes
I think this is the right direction for better exception handling. Thanks!

2021-08-16 15:10 UTC, themarpe commented on include/depthai/xlink/XLinkStream.hpp
> +    using std::runtime_error::runtime_error;
Could add a field something along the lines of:
`XLinkError_t xlinkError` / `XLinkError_t status`
And populate with returned status for extra information to be passed down.

2021-08-16 15:11 UTC, themarpe commented
@kunaltyagi Python bindings can be done in same manner, separate branch, targeting develop, which complements changes in core branch. When core is merged, so is the branch in bindings and submodules are again updates as necessary. (bindings branch points to this branch commit before hand)

2021-08-16 15:21 UTC, kunaltyagi commented
![image](https://user-images.githubusercontent.com/2657068/129587856-03857e23-a32e-43da-a321-d9e70812af0e.png)
There are no bindings for XLinkStream

2021-08-16 15:37 UTC, kunaltyagi commented on include/depthai/xlink/XLinkStream.hpp
> +    using std::runtime_error::runtime_error;
What would the API look like? Should the ctor change? Should the string message be moved to the what function?

2021-08-16 16:02 UTC, themarpe commented on include/depthai/xlink/XLinkStream.hpp
> +    using std::runtime_error::runtime_error;
Hmm, I'd go with an additional ctor:
`XLinkError::XLinkError(XLinkError_t, std::string/const char* msg)`

otherwise the field can be accessed publicly for consumption (or for setting to another value, etc...).

2021-08-16 16:03 UTC, themarpe commented on include/depthai/xlink/XLinkStream.hpp
> +    using std::runtime_error::runtime_error;
And default ctors would just leave the field as is - which could have default value of `X_LINK_ERROR`

2021-08-16 16:33 UTC, kunaltyagi commented on include/depthai/xlink/XLinkStream.hpp
> +    using std::runtime_error::runtime_error;
Made some changes to the API. PTAL (No default ctor: doesn't make sense in the use-case right now)

2021-08-16 16:52 UTC, kunaltyagi commented
https://github.com/luxonis/depthai-python/pull/345

2021-08-16 16:59 UTC, themarpe requested changes

2021-08-16 16:59 UTC, themarpe commented on include/depthai/xlink/XLinkStream.hpp
> +};
Retain option capability to set message - otherwise default is used.
(& naming convention for parameters, remove ending `_`)

2021-08-16 23:30 UTC, kunaltyagi commented on include/depthai/xlink/XLinkStream.hpp
> +};
Suggested names for arguments?

2021-08-17 08:44 UTC, themarpe commented on include/depthai/xlink/XLinkStream.hpp
> +};
Can just remove the trailing `_`. Should shadow correctly AFAIK. Otherwise any abbreviation (status->s, streamName->stream/name, message->msg)
```
struct XLinkError : public std::runtime_error {
    const XLinkError_t status = 0;
    const std::string streamName;

    using std::runtime_error::runtime_error;

    XLinkError(XLinkError_t status, const std::string& streamName, const std::string& message)
        : runtime_error(message), status(status), streamName(streamName) {}
};

struct XLinkReadError : public XLinkError {
    XLinkReadError(XLinkError_t status, const std::string& streamName);
};
struct XLinkWriteError : public XLinkError {
    XLinkWriteError(XLinkError_t status, const std::string& streamName);
};
```

2021-08-18 01:49 UTC, kunaltyagi commented
It should be ready for a merge

2021-08-18 02:13 UTC, themarpe approved these changes
Thanks!

2021-08-24 02:03 UTC, kunaltyagi commented
Can we get this merged?

2021-08-24 10:58 UTC, themarpe commented
@kunaltyagi 
I've fixed an incorrect set exception messages and added bindings in python.
Will merge after release, today/tomorrow.

Thanks!

2021-08-25 00:11 UTC, merged