Added getting calculated FOV from intrinsics
luxonis/depthai-core pull request #206
Opened 2021-09-02 14:44 UTC by Erol444

Output from the example about FOV:
`Mono FOV from camera specs: 71.86, calculated FOV: 73.0632`

Matrix printing in example:
```Extrinsics from rgb->right test:
[[0.999971, 0.007518, -0.001316, -3.748613]
[-0.007519, 0.999971, -0.000848, 0.061079]
[0.001310, 0.000858, 0.999999, 0.105437]
[0.000000, 0.000000, 0.000000, 1.000000]]

Extrinsics from left->rgb test:
[[0.999886, -0.008687, -0.012368, -3.802770]
[0.008607, 0.999942, -0.006518, -0.054966]
[0.012424, 0.006411, 0.999902, -0.070479]
[0.000000, 0.000000, 0.000000, 1.000000]]```

2021-09-02 14:56 UTC, alex-luxonis reviewed
Some checks are failing, run `make clangformat`

2021-09-02 14:56 UTC, alex-luxonis commented on src/device/CalibrationHandler.cpp
> +#include <math.h>
Better to `#include <cmath>` ?

2021-09-02 14:56 UTC, alex-luxonis commented on src/device/CalibrationHandler.cpp
> +        if(eepromData.cameraData.find(cameraId) == eepromData.cameraData.end())
This check may need to be moved outside, to apply also for `useSpec == false`.

2021-09-02 15:38 UTC, saching13 commented on src/device/CalibrationHandler.cpp
> +    std::tie(intrinsics, width, height) = CalibrationHandler::getDefaultIntrinsics(dai::CameraBoardSocket::LEFT);
hardcoded to `dai::CameraBoardSocket::LEFT` here

2021-09-02 16:57 UTC, Erol444 commented on src/device/CalibrationHandler.cpp
> +        if(eepromData.cameraData.find(cameraId) == eepromData.cameraData.end())
ah thought it doesn't need `eepromData` to get intrinsic (or that the check is there as well). Will fix.

2021-09-21 00:02 UTC, themarpe requested changes

2021-09-21 00:02 UTC, themarpe commented on src/device/CalibrationHandler.cpp
> +#include <cmath>
```
#define _USE_MATH_DEFINES
#include <cmath>
```

2021-09-30 18:36 UTC, themarpe approved these changes

2021-10-02 12:07 UTC, merged