Fix the inversion formula for extrinsic matrices in CalibrationHandler
luxonis/depthai-core pull request #212
Opened 2021-09-16 20:32 UTC by oseiskar

A rigid body transform (extrinsic matrix) corresponding to a rotation R and translation t is inverted as (R, t) -> (R<sup>T</sup>, -R<sup>T</sup> t). The current version had (R, t) -> (R<sup>T</sup>, -t), (which is rather close if R is close to identity).

**How to reproduce the problem**: Run the `calibration_reader.cpp` demo.

**Before** (relevant part)

> Extrinsics from left->right test ->
> 0.999915  -0.00947824  0.00895108  -7.47418
> 0.009468  0.999954  0.00118608  -0.0847316
> -0.00896192  -0.00110123  0.999959  0.106084
> 0  0  0  1
> Extrinsics from right->left test ->
> 0.999915  0.009468  -0.00896192  _7.47418_
> -0.00947824  0.999954  -0.00110123  _0.0847316_
> 0.00895108  0.00118608  0.999959  _-0.106084_
> 0  0  0  1

**After**
> Extrinsics from left->right test ->
> 0.999915  -0.00947824  0.00895108  -7.47418
> 0.009468  0.999954  0.00118608  -0.0847316
> -0.00896192  -0.00110123  0.999959  0.106084
> 0  0  0  1
> Extrinsics from right->left test ->
> 0.999915  0.009468  -0.00896192  **7.4753**
> -0.00947824  0.999954  -0.00110123  **0.0140025**
> 0.00895108  0.00118608  0.999959  **-0.0390775**
> 0  0  0  1

Check with Numpy:
```python
import numpy as np

fwd = np.array([ # Extrinsics from left->right test
    [0.999915,  -0.00947824,  0.00895108,  -7.47418],
    [0.009468 , 0.999954,  0.00118608,  -0.0847316],
    [-0.00896192,  -0.00110123,  0.999959,  0.106084],
    [0,  0,  0,  1]
])

print(np.linalg.inv(fwd))
```
```
[[ 9.99915034e-01  9.46800107e-03 -8.96191671e-03  7.47529790e+00]
 [-9.47824825e-03  9.99954948e-01 -1.10123116e-03  1.40024722e-02]
 [ 8.95108780e-03  1.18608048e-03  9.99959470e-01 -3.90771604e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```

2021-09-29 17:16 UTC, saching13 approved these changes

2021-09-29 17:57 UTC, saching13 requested changes
Thanks for the PR.
Can you fix the styling for this?

2021-09-30 18:19 UTC, saching13 approved these changes

2021-09-30 18:20 UTC, saching13 commented
@themarpe  should we change the dest to develop ?

2021-09-30 18:41 UTC, themarpe commented
Good catch @saching13 - yes, lets do develop first.

2021-09-30 18:44 UTC, merged