Gen2: add MonoCamera and StereoDepth nodes
luxonis/depthai-core pull request #23
Opened 2020-11-23 15:07 UTC by alex-luxonis

Related PR: https://github.com/luxonis/depthai-shared/pull/10

2020-11-23 18:06 UTC, themarpe requested changes
LGTM apart from checks failing.
For style, run the `clangformat` target to modify style according to clang format style file (warning, it modifies in place, make sure to commit before, in case something goes wrong)
```
cmake --build [path/to/build/dir] --target clangformat
```

2020-11-29 01:09 UTC, themarpe requested changes

2020-11-29 01:09 UTC, themarpe commented on include/depthai/pipeline/node/StereoDepth.hpp
> +    Input right{*this, "right", Input::Type::SReceiver, {{DatatypeEnum::Buffer, true}}};
This is fixed now in gen2_imagemanip. Check method `canConnect`. Preferably set back to ImgFrame and apply the fix from gen2_imagemanip to `canConnect`

2020-11-30 20:53 UTC, alex-luxonis commented on include/depthai/pipeline/node/StereoDepth.hpp
> +    Input right{*this, "right", Input::Type::SReceiver, {{DatatypeEnum::Buffer, true}}};
Done. Thanks!

2020-12-08 14:49 UTC, themarpe commented
Merged to `gen2_develop`

2020-12-10 14:14 UTC, alex-luxonis commented
Reopening to change target branch, to get marked as "merged".

2020-12-10 14:15 UTC, merged