ImageManip: add support for rotated/arbitrary cropping
luxonis/depthai-core pull request #38
Opened 2021-01-12 20:12 UTC by alex-luxonis

Related PR: https://github.com/luxonis/depthai-shared/pull/16

2021-01-13 10:45 UTC, themarpe requested changes
Can you add a test/example of this as well?
And some additional helper functions like:
 - rotate (degrees / radians)
 - etc..

2021-02-08 20:06 UTC, Luxonis-Brandon commented
This is looking to have so much awesome functionality!  Thanks @alex-luxonis !  
When do you think will be ready to merge?  It looks like from the last commit you may be already preparing it for merge?

2021-02-09 14:23 UTC, themarpe requested changes
For `ColorCamera` and `ImageManip` should we rather add setInitialConfig taking in an corresponding message? Or reference return `getInitialConfig`
This depends on whether all options can be configured initially. And I think that right now `ColorCamera` is missing some initial settings

2021-02-11 23:21 UTC, themarpe approved these changes

2021-02-12 05:09 UTC, szabi-luxonis requested changes

2021-02-12 05:09 UTC, szabi-luxonis commented on src/pipeline/node/NeuralNetwork.cpp
> +    properties.numThreads = numThreads;
Can you add a check and throw error if this is not in valid range? 1 or 2 should be the only valid values.

2021-02-12 14:37 UTC, themarpe commented on src/pipeline/node/NeuralNetwork.cpp
> +    properties.numThreads = numThreads;
Also the 'AUTO' value (0 or -1, TBD). And a getter, for later depthai-gui usage

2021-02-12 15:26 UTC, alex-luxonis commented on src/pipeline/node/NeuralNetwork.cpp
> +    properties.numThreads = numThreads;
So discussed internally, and depending on the NN blob, if it only uses Shaves and no NCEs, it may make sense to run on more threads (e.g. we could have 12 Shaves available, and the blob needs 3, then could have up to 4 threads, while setting more would work, but may not be optimal).
So decided to add more complex checks on device side regarding this field, and issue a warning if the value is larger than optimal.

Added a getter for this field for now. Some other fields in NeuralNetwork properties also need getters, we'll add later.

2021-02-12 19:15 UTC, alex-luxonis commented
Updated PR description with a list of changes. Merging.

2021-02-12 19:15 UTC, merged