Enhance stereo depth develop merge
luxonis/depthai-core pull request #4
Opened 2020-09-10 16:39 UTC by iamsg-luxonis

Enhance stereo depth develop merge

2020-09-10 21:13 UTC, themarpe requested changes

2020-09-10 21:13 UTC, themarpe commented on include/depthai/device.hpp
> +    std::vector<float> get_Translation();
Rename to `get_translation`

2020-09-10 21:13 UTC, themarpe commented on include/depthai/host_data_packet.hpp
> +            if (stream_name_ == "disparity_color") // FIXME see if applicable to all streams
metadata.frameSize should be set correctly. Maybe rather fix over at device side instead?

2020-09-10 21:31 UTC, iamsg-luxonis commented on include/depthai/host_data_packet.hpp
> +            if (stream_name_ == "disparity_color") // FIXME see if applicable to all streams
"disparity_color" is a virtual stream, created on the host ("disparity" colorized on host)

2020-09-10 21:42 UTC, themarpe commented on include/depthai/host_data_packet.hpp
> +            if (stream_name_ == "disparity_color") // FIXME see if applicable to all streams
Can you add the metadata to the frame while creating it and then send it onwards to "disparity_color" stream. Then decoded data will include everything needed - w/h, type, ...

2020-09-10 23:00 UTC, iamsg-luxonis commented on include/depthai/host_data_packet.hpp
> +            if (stream_name_ == "disparity_color") // FIXME see if applicable to all streams
I don't know why it was added here, but I agree, it should be added when it's created.
I will change it.

2020-09-15 16:53 UTC, alex-luxonis commented on include/depthai/host_data_packet.hpp
> +            if (stream_name_ == "disparity_color") // FIXME see if applicable to all streams
Fixed.

2020-09-15 22:42 UTC, merged