Detection NN example
luxonis/depthai-core pull request #50
Opened 2021-02-08 13:26 UTC by szabi-luxonis

Added getLayerInt32
Added mobilenet device side decoding example
Added tiny yolo v3 device side decoding example
Improved Detection network API

2021-02-09 15:25 UTC, themarpe requested changes
LGTM apart from the requested changes.
Rationally behind the ImgDetections move from reference to getter?
And in case it remains, add a setter as well to be able to create ImgDetections message and send it to the device

2021-02-09 15:25 UTC, themarpe commented on include/depthai/pipeline/node/DetectionNetwork.hpp
> +    Output passthrough{*this, "passthrough", Output::Type::MSender, {{DatatypeEnum::Buffer, true}}};
`DatatypeEnum::ImgFrame, true` same as input (if it really does passthrough input only)

2021-02-09 15:25 UTC, themarpe commented on examples/src/camera_mobilenet_example.cpp
> +    if (syncNN)
Inline or `{}`

2021-02-09 15:25 UTC, themarpe commented on include/depthai/pipeline/datatype/ImgDetections.hpp
> +    std::vector<ImgDetection> getDetections(void) const;
```
std::vector<ImgDetection> getDetections() const;
```

2021-02-09 15:27 UTC, themarpe commented on include/depthai/pipeline/node/DetectionNetwork.hpp
>      Output out{*this, "out", Output::Type::MSender, {{DatatypeEnum::Buffer, false}}};
This should be `DatatypeEnum::ImgDetections`

2021-02-09 15:35 UTC, themarpe commented on include/depthai/pipeline/Pipeline.hpp
> +    void setPipelineOpenVINOVersion(OpenVINO::Version version) {
I'd rather go with `setOpenVINOVersion` as Pipeline is infered context.

2021-02-12 10:05 UTC, szabi-luxonis commented
> LGTM apart from the requested changes.
> Rationally behind the ImgDetections move from reference to getter?
> And in case it remains, add a setter as well to be able to create ImgDetections message and send it to the device

Switched back to reference, fixed setNumFramePools for detection NN, fixed exit on `q` press (waitkey) in all examples.

2021-02-12 14:34 UTC, themarpe approved these changes

2021-02-15 09:30 UTC, merged