Add confirmation that the device has booted up
luxonis/depthai-core pull request #51
Opened 2021-02-09 07:57 UTC by kunaltyagi

Found useful while debugging:
```
$ ./examples/system_information 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to find device after booting, error message: X_LINK_DEVICE_NOT_FOUND
Aborted (core dumped)
$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 011: ID 03e7:2485  
Bus 001 Device 002: ID 04f3:0103 Elan Microelectronics Corp. ActiveJet K-2024 Multimedia Keyboard
```

2021-02-09 12:58 UTC, Luxonis-Brandon commented
Thanks @kunaltyagi !

2021-02-09 21:29 UTC, themarpe requested changes
Thanks for the PR - will merge after mentioned changes

2021-02-09 21:29 UTC, themarpe commented on src/xlink/XLinkConnection.cpp
> +        bool boot_status;
Change to `bootStatus` (camelCase is our preferred variable naming convention)

2021-02-10 10:25 UTC, themarpe approved these changes

2021-02-10 10:28 UTC, merged