Gen2 OpenCV Support
luxonis/depthai-core pull request #53
Opened 2021-02-11 00:50 UTC by themarpe

Added support for cv::Mat types being requested from ImgFrame.
Support is optional and can also be completely disabled.

Additional target is now created, depthai::core::opencv, which links to depthai::core and adds the OpenCV functionality.

This enables/will enable better UX when dealing with ImgFrames coming/going to device.

2021-02-11 02:56 UTC, szabi-luxonis requested changes

2021-02-11 02:56 UTC, szabi-luxonis commented on src/opencv/ImgFrame.cpp
> +        case Type::RAW8:
RAW16, GRAY16 can also be added as CV_16UC1

2021-02-22 18:21 UTC, szabi-luxonis commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.4) # For Hunter
For what we need cmake 3.4 ? On slightly older system with the default cmake it won't work.

2021-02-22 18:21 UTC, szabi-luxonis commented on src/opencv/ImgFrame.cpp
> +        case Type::RAW8:
Should we throw error in case it's not possible, since it's not the desired effect? (Function not used properly)

2021-02-22 18:48 UTC, themarpe commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.4) # For Hunter
The change was for `IN_LIST` operator. And right now AFAIK a couple of our dependencies require higher anyway. I'd have to create a separate build with actual `cmake` of that version to verify correctness of this (some behavior can also change with newer versions)

2021-02-22 18:50 UTC, themarpe commented on src/opencv/ImgFrame.cpp
> +        case Type::RAW8:
For RAW8, RAW16, etc...?
Maybe the function name is ill formed, but I had in mind that the return of this function gives you frame that opencv can "atleast" display. So thats why I counted in grayscale, etc..

Should I rather rename the function?

2021-02-25 09:02 UTC, merged