Added an example with multiple devices
luxonis/depthai-core pull request #556
Opened 2022-08-15 20:25 UTC by moratom

A simple example on how to use multiple devices with depthai.
It is a 1:1 rewrite of the python example found [here].(https://github.com/luxonis/depthai-experiments/blob/master/gen2-multiple-devices/main.py)

2022-08-15 22:13 UTC, themarpe requested changes

2022-08-15 22:13 UTC, themarpe commented on examples/CMakeLists.txt
> +dai_add_example(multidevice_example mixed/multidevice_example.cpp OFF)
Eg: `multiple_devices`

Examples don't have `_example` appended to it (unlike tests)

2022-08-15 22:13 UTC, themarpe commented on examples/mixed/multidevice_example.cpp
> +std::shared_ptr<dai::Pipeline> getPipeline(std::string& deviceType) {
`createPipeline`

2022-08-15 22:13 UTC, themarpe commented on examples/mixed/multidevice_example.cpp
> +        std::cout << std::endl;
```
std::cout << usb_speed << std::endl;
```

2022-08-15 22:13 UTC, themarpe commented on examples/mixed/multidevice_example.cpp
> +        }
These aren't correct assumption to make.
PoE/non-PoE would be better checked by `deviceInfo.protocol == X_LINK_TCP_IP`
And for the actual device, use `readCalibration2` and extract the boardName / productName (if available) and / or necessary

2022-08-15 22:13 UTC, themarpe commented on examples/mixed/multidevice_example.cpp
> +    auto usb2mode = false;
```
const auto usbSpeed = dai::UsbSpeed::SUPER;
```

2022-08-15 22:13 UTC, themarpe commented on examples/mixed/multidevice_example.cpp
> +    std::map<std::string, std::shared_ptr<dai::DataOutputQueue>> q_rgb_map;
Naming - use CamelCase consistentently throughout the example
Eg:
```
qRgbMap
```

2022-08-15 23:36 UTC, moratom commented on examples/mixed/multidevice_example.cpp
> +    std::map<std::string, std::shared_ptr<dai::DataOutputQueue>> q_rgb_map;
Fixed in commit `06507ff`.

2022-08-15 23:36 UTC, moratom commented on examples/mixed/multidevice_example.cpp
> +    auto usb2mode = false;
Fixed in commit `06507ff`.

2022-08-15 23:38 UTC, moratom commented on examples/mixed/multidevice_example.cpp
> +        }
I simplified the example and removed this logic + added the `boardName` and `productName` in the printout for additional information.

2022-08-15 23:38 UTC, moratom commented on examples/mixed/multidevice_example.cpp
> +        std::cout << std::endl;
Fixed in commit `06507ff`.

2022-08-15 23:38 UTC, moratom commented on examples/mixed/multidevice_example.cpp
> +std::shared_ptr<dai::Pipeline> getPipeline(std::string& deviceType) {
Fixed in commit `06507ff`.

2022-08-17 16:52 UTC, themarpe approved these changes

2022-08-17 17:22 UTC, merged