Neural network and detection parser support
luxonis/depthai-core pull request #560
Opened 2022-08-17 17:55 UTC by moratom

Neural network and detection parser support for S3.

2022-08-17 22:53 UTC, themarpe requested changes

2022-08-17 22:53 UTC, themarpe commented on examples/tmp/tmp_detection_parser_mobilenet.cpp
> +#define MIN_SCORE 0.3
```suggestion
static constexpr auto MODEL_IN_WIDTH = 512;
static constexpr auto MODEL_IN_HEIGHT = 512;

static constexpr auto MIN_SCORE = 0.3;
```

2022-08-17 22:53 UTC, themarpe commented on examples/tmp/tmp_detection_parser_mobilenet.cpp
> +#define MIN_SCORE 0.3
Likewise elsewhere - no need for `#define`

2022-08-17 22:53 UTC, themarpe commented on examples/tmp/tmp_nn.cpp
> +    using namespace std;
Redundant

2022-08-17 22:53 UTC, themarpe commented on include/depthai/openvino/OpenVINO.hpp
> +    enum Device { VPU, VPUX };
```suggestion
    enum class Device { VPU, VPUX };
```

As it then reads: `OpenVINO::Device::VPU / VPUX` instead of `OpenVINO::VPU / VPUX`

2022-08-17 22:53 UTC, themarpe commented on include/depthai/openvino/OpenVINO.hpp
> +    enum Device { VPU, VPUX };
Version was done as regular enum intentional as name includes the `VERSION_` prefix, as number otherwise isn't a valid starting character in enum name

2022-08-17 22:53 UTC, themarpe commented on src/openvino/OpenVINO.cpp
> +    std::vector<uint8_t> S3Header{0X18, 0X0, 0X0, 0X0, 0X42, 0X4C, 0X4F, 0X42};
```suggestion
    std::vector<uint8_t> vpuxBlobHeader{0X18, 0X0, 0X0, 0X0, 0X42, 0X4C, 0X4F, 0X42};
```

2022-08-17 22:53 UTC, themarpe commented on src/pipeline/Node.cpp
> +    }
Seems to be duplicated of previous loadResourceCwd and PipelineImpl::loadResourceCwd.

IMO could be left as is, with eahc node calling the `cwd` of itself along, and PipelineImpl handling then everything (/w protocol handling as well)

2022-08-17 22:53 UTC, themarpe commented on src/pipeline/node/NeuralNetwork.cpp
> +    properties.modelSource = NeuralNetworkProperties::ModelSource::XML_API;
```suggestion
    properties.modelSource = Properties::ModelSource::XML;
```

:+1: 
But setBlobPath is missing the same call but setting back to `Properties::ModelSource::BLOB;`

2022-08-17 22:53 UTC, themarpe commented on examples/tmp/tmp_detection_parser_yolo.cpp
> +        auto tensor = std::make_shared<dai::RawBuffer>();
Can just be `dai::Buffer tensor;`

2022-08-17 22:53 UTC, themarpe commented on examples/tmp/tmp_detection_parser_mobilenet.cpp
> +        cv::Mat resized_frame = resizeKeepAspectRatio(frame, cv::Size(MODEL_IN_WIDTH, MODEL_IN_HEIGHT), cv::Scalar(0));
resizedFrame

2022-08-17 22:53 UTC, themarpe commented on examples/tmp/tmp_detection_parser_mobilenet.cpp
> +        auto inDet = detections->tryGet<dai::ImgDetections>();
Might want to check `tryGetAll` here or just `get`

2022-08-17 23:21 UTC, moratom commented on src/device/DeviceBase.cpp
> +        pimpl->rpcClient->call("readAssetStorageFromXLink", streamAssetStorage, assetStorage.size());
Should this be handled in core or updated on S1/S2 firmware?

2022-08-17 23:22 UTC, moratom commented on include/depthai/openvino/OpenVINO.hpp
> +    enum Device { VPU, VPUX };
Makes sense yes, I will fix those.

2022-08-17 23:43 UTC, moratom commented on src/pipeline/Node.cpp
> +    }
Yeah makes sense, I had to put "check if path is absolute" somewhere, but didn't give enough thought where that should be. I will refactor.

2022-08-18 14:51 UTC, moratom commented on src/pipeline/Node.cpp
> +    }
I refactored it on `09f6baa5d2f` @themarpe

2022-08-23 22:46 UTC, merged