Add a setter and a getter directly for EEPROM data
luxonis/depthai-core pull request #603
Opened 2022-10-03 15:11 UTC by moratom

Needed for RVC3 eeprom port.

2022-10-03 15:13 UTC, moratom commented on include/depthai/pipeline/ThreadedNode.hpp
> +#include "depthai/pipeline/Pipeline.hpp"
I made this change, because otherwise all nodes need to include the `Pipeline.hpp` to use `getParentPipeline()` since it is just forward declared in `Node.hpp` to avoid circular includes.

2022-10-03 18:12 UTC, themarpe requested changes

2022-10-03 18:12 UTC, themarpe commented on src/pipeline/Pipeline.cpp
> +}
```suggestion
tl::optional<EepromData> PipelineImpl::getEepromData() const {
    return globalProperties.calibData;
}
```

For this one, as we don't have to retain API

2022-10-04 15:01 UTC, themarpe requested changes
Just to be complete - the suggested change will allow to 'unset' EepromData with eg:
```
pipeline.setEepromData(tl::nullopt_t)
```
or empty optional (AFAIK)
```
pipeline.setEepromData({})
```

2022-10-17 19:07 UTC, merged