NNData refactor
luxonis/depthai-core pull request #643
Opened 2022-11-17 02:09 UTC by whoactuallycares

2022-12-02 17:13 UTC, themarpe requested changes
@moratom 
Do you mind switching to Hunter instead of submodules and cherrypicking the bugfix from rvc3 branch?

2022-12-02 17:17 UTC, themarpe commented on include/depthai/pipeline/datatype/NNData.hpp
> +
I assume this errors come from xtensor itself?

2022-12-02 17:20 UTC, whoactuallycares commented on include/depthai/pipeline/datatype/NNData.hpp
> +
Yes. I did this since turning it off for the entire project seemed like a bad idea

2022-12-02 17:36 UTC, whoactuallycares commented
> @moratom Do you mind switching to Hunter instead of submodules and cherrypicking the bugfix from rvc3 branch?

When I pull xtensor requires xtl to be installed. When building xtensor with hunter it throws an error about xtl missing even though it's included before it. I tried to make it work but I didn't want to spend too much time on it so I fell back to submodules

2022-12-02 17:39 UTC, themarpe commented on include/depthai/pipeline/datatype/NNData.hpp
> +
Do you mind sending over the error log?

2022-12-02 18:00 UTC, whoactuallycares commented on include/depthai/pipeline/datatype/NNData.hpp
> +
-- Generating new toolchain...
-- Using toolchain file: /home/tommy/projects/luxonis/depthai-core/build/generated/toolchain.cmake
-- The CXX compiler identification is Clang 14.0.6
-- The C compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /home/tommy/.hunter
-- [hunter] [ Hunter-ID: cb0ea1f | Toolchain-ID: af5c337 | Config-ID: 052dbf3 ]
-- [hunter] NLOHMANN_JSON_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 3.9.1)
-- [hunter] Cache HIT: nlohmann_json
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/nlohmann_json/3.9.1/f8a20a7/151cbba/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] XLINK_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: luxonis-2021.4.2-develop)
-- [hunter] Cache HIT: XLink
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/XLink/luxonis-2021.4.2-develop/25fba41/da39a3e/a23c16c/da39a3e/2a67cc2/cache.sha1
-- [hunter] LIBUSB-LUXONIS_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 1.0.24-cmake)
-- [hunter] Cache HIT: libusb-luxonis
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/libusb-luxonis/1.0.24-cmake/2d79573/7b36c59/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] BZIP2_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 1.0.8-p0)
-- [hunter] Cache HIT: BZip2
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/BZip2/1.0.8-p0/9125bd6/fa7ae1a/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] FP16_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: luxonis-0.0.0)
-- [hunter] Cache HIT: FP16
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/FP16/luxonis-0.0.0/40e9723/16119be/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] LIBARCHIVE-LUXONIS_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: hunter-3.5.2)
-- [hunter] Cache HIT: libarchive-luxonis
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/libarchive-luxonis/hunter-3.5.2/ca5cd0f/92a4469/a23c16c/da39a3e/62d2b8c/cache.sha1
-- [hunter] LZMA_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 5.2.3-p4)
-- [hunter] Cache HIT: lzma
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/lzma/5.2.3-p4/09d7d8c/da39a3e/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] SPDLOG_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 1.8.2)
-- [hunter] Cache HIT: spdlog
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/spdlog/1.8.2/4437f35/2438b6e/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] ZLIB_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 1.2.11-p2)
-- [hunter] Cache HIT: ZLIB
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/ZLIB/1.2.11-p2/fb8b648/da39a3e/a23c16c/e5fa44f/da39a3e/cache.sha1
-- [hunter] BACKWARD_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 1.6)
-- [hunter] Cache HIT: Backward
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/Backward/1.6/4ecb711/8a442bf/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] LIBNOP_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 1.0-ec8f75a)
-- [hunter] Cache HIT: libnop
-- [hunter] Cache info: /home/tommy/.hunter/_Base/Cache/meta/af5c337/libnop/1.0-ec8f75a/32f40f0/da39a3e/a23c16c/da39a3e/da39a3e/cache.sha1
-- [hunter] XTL_ROOT: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Install (ver.: 0.7.4)
-- [hunter] Building xtl
loading initial cache file /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/cache.cmake
loading initial cache file /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/args.cmake
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is Clang 14.0.6
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Build
[ 12%] Creating directories for 'xtl-Release'
[ 25%] Performing download step (download, verify and extract) for 'xtl-Release'
-- verifying file...
       file='/home/tommy/.hunter/_Base/Download/xtl/0.7.4/1d0077e/0.7.4.tar.gz'
-- File already exists and hash match (skip download):
  file='/home/tommy/.hunter/_Base/Download/xtl/0.7.4/1d0077e/0.7.4.tar.gz'
  SHA1='1d0077e075c05021926086be69502b88473011f7'
-- extracting...
     src='/home/tommy/.hunter/_Base/Download/xtl/0.7.4/1d0077e/0.7.4.tar.gz'
     dst='/home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No update step for 'xtl-Release'
[ 50%] No patch step for 'xtl-Release'
[ 62%] Performing configure step for 'xtl-Release'
loading initial cache file /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/cache.cmake
loading initial cache file /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/args.cmake
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is Clang 14.0.6
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- xtl v0.7.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Build/xtl-Release-prefix/src/xtl-Release-build
[ 75%] Performing build step for 'xtl-Release'
[ 87%] Performing install step for 'xtl-Release'
Install the project...
-- Install configuration: "Release"
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xany.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xbasic_fixed_string.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xbase64.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xclosure.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xcomplex.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xcomplex_sequence.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xspan.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xspan_impl.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xdynamic_bitset.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xfunctional.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xhalf_float.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xhalf_float_impl.hpp
-- Installing: /home/tommy/.hunter/_Base/cb0ea1f/af5c337/052dbf3/Build/xtl/Install/include/xtl/xhash.hpp
-- Installing: /home/tommy/.hunter/_Base/cb [...]

2022-12-05 15:01 UTC, themarpe commented on include/depthai/pipeline/datatype/NNData.hpp
> +
Unrelated log - I meant the one that is caused if above suppression is missing.

Also for future reference, format such messages with triple backtick, otherwise the visualization is all over the place

2022-12-05 18:36 UTC, whoactuallycares commented on include/depthai/pipeline/datatype/NNData.hpp
> +
```
[  1%] Generating intermediate file for /home/tommy/downloads/depthai-core/build/resources/depthai-device-fwp-b3aeaf23ff5857fc8f79d412ceefc08da23e7aad.tar.xz
[  1%] Generating depthai-resources resource loader
[  1%] Generating intermediate file for /home/tommy/downloads/depthai-core/build/resources/depthai-bootloader-fwp-0.0.21.tar.xz
[  1%] Building CXX object examples/CMakeFiles/utility.dir/utility/utility.cpp.o
[  2%] Building CXX object CMakeFiles/depthai-resources.dir/__cmrc_depthai-resources/lib.cpp.o
[  2%] Building CXX object CMakeFiles/depthai-resources.dir/__cmrc_depthai-resources/intermediate/depthai-device-fwp-b3aeaf23ff5857fc8f79d412ceefc08da23e7aad.tar.xz.cpp.o
[  2%] Building CXX object CMakeFiles/depthai-resources.dir/__cmrc_depthai-resources/intermediate/depthai-bootloader-fwp-0.0.21.tar.xz.cpp.o
[  2%] Linking CXX static library libdepthai-resources.a
[  2%] Built target depthai-resources
[  2%] Building CXX object CMakeFiles/depthai-core.dir/shared/depthai-shared/src/utility/Checksum.cpp.o
[  2%] Building C object CMakeFiles/depthai-core.dir/shared/depthai-bootloader-shared/src/SBR.c.o
[  4%] Building CXX object CMakeFiles/depthai-core.dir/src/device/Device.cpp.o
[  4%] Building CXX object CMakeFiles/depthai-core.dir/shared/depthai-bootloader-shared/src/Bootloader.cpp.o
[  5%] Building CXX object CMakeFiles/depthai-core.dir/shared/depthai-shared/src/datatype/DatatypeEnum.cpp.o
[  5%] Building CXX object CMakeFiles/depthai-core.dir/src/device/DeviceBase.cpp.o
[  5%] Building CXX object CMakeFiles/depthai-core.dir/src/device/DeviceBootloader.cpp.o
[  6%] Building CXX object CMakeFiles/depthai-core.dir/src/device/DataQueue.cpp.o
[  6%] Building CXX object CMakeFiles/depthai-core.dir/src/device/CallbackHandler.cpp.o
[  6%] Building CXX object CMakeFiles/depthai-core.dir/src/device/CalibrationHandler.cpp.o
[  6%] Building CXX object CMakeFiles/depthai-core.dir/src/device/Version.cpp.o
[  8%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/Pipeline.cpp.o
[  9%] Linking CXX static library libutility.a
[  9%] Built target utility
[  9%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/AssetManager.cpp.o
[  9%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/Node.cpp.o
[  9%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/XLinkIn.cpp.o
[ 10%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/XLinkOut.cpp.o
[ 10%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/ColorCamera.cpp.o
[ 10%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/MonoCamera.cpp.o
[ 10%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/StereoDepth.cpp.o
[ 12%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/NeuralNetwork.cpp.o
[ 12%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/ImageManip.cpp.o
[ 12%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/Warp.cpp.o
[ 13%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/DetectionNetwork.cpp.o
[ 13%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/VideoEncoder.cpp.o
[ 13%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/Script.cpp.o
[ 13%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/SpatialDetectionNetwork.cpp.o
[ 13%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/SystemLogger.cpp.o
[ 15%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/SpatialLocationCalculator.cpp.o
[ 15%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/AprilTag.cpp.o
[ 15%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/ObjectTracker.cpp.o
[ 15%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/IMU.cpp.o
[ 16%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/EdgeDetector.cpp.o
[ 16%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/SPIIn.cpp.o
[ 16%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/FeatureTracker.cpp.o
[ 16%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/node/DetectionParser.cpp.o
[ 17%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/Buffer.cpp.o
[ 17%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/ImgFrame.cpp.o
[ 17%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/ImageManipConfig.cpp.o
[ 19%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/CameraControl.cpp.o
[ 19%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/NNData.cpp.o
[ 19%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/ImgDetections.cpp.o
[ 19%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/SpatialImgDetections.cpp.o
[ 20%] Building CXX object CMakeFiles/depthai-core.dir/src/pipeline/datatype/SystemInformation.cpp.o
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp: In member function ‘bool dai::NNData::getLayerDatatype(const string&, dai::TensorInfo::DataType&) const’:
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:184:29: warning: ‘bool dai::NNData::getLayer(const string&, dai::TensorInfo&) const’ is deprecated: Use 'getTensor()' instead [-Wdeprecated-declarations]
     if(getLayer(name, tensor)) {
                             ^
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:165:6: note: declared here
 bool NNData::getLayer(const std::string& name, TensorInfo& tensor) const {
      ^~~~~~
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp: In member function ‘std::vector<unsigned char> dai::NNData::getLayerUInt8(const string&) const’:
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:196:29: warning: ‘bool dai::NNData::getLayer(const string&, dai::TensorInfo&) const’ is deprecated: Use 'getTensor()' instead [-Wdeprecated-declarations]
     if(getLayer(name, tensor)) {
                             ^
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:165:6: note: declared here
 bool NNData::getLayer(const std::string& name, TensorInfo& tensor) const {
      ^~~~~~
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp: In member function ‘std::vector<int> dai::NNData::getLayerInt32(const string&) const’:
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:214:29: warning: ‘bool dai::NNData::getLayer(const string&, dai::TensorInfo&) const’ is deprecated: Use 'getTensor()' instead [-Wdeprecated-declarations]
     if(getLayer(name, tensor)) {
                             ^
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:165:6: note: declared here
 bool NNData::getLayer(const std::string& name, TensorInfo& tensor) const {
      ^~~~~~
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp: In member function ‘std::vector<float> dai::NNData::getLayerFp16(const string&) const’:
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:238:29: warning: ‘bool dai::NNData::getLayer(const string&, dai::TensorInfo&) const’ is deprecated: Use 'getTensor()' instead [-Wdeprecated-declarations]
     if(getLayer(name, tensor)) {
                             ^
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:165:6: note: declared here
 bool NNData::getLayer(const std::string& name, TensorInfo& tensor) const {
      ^~~~~~
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp: In member function ‘std::vector<unsigned char> dai::NNData::getFirstLayerUInt8() const’:
/home/tommy/downloads/depthai-core/src/pipeline/datatype/NNData.cpp:262:51: warning: ‘std::vector<unsigned char> dai::NNData::getLayerUInt8(const string&) const’ is deprecated: Use 'getTensor()' instead [-Wdeprecated-declarations]
         return getLayerUInt8(rawNn.tensors[0].name);
                                                   ^
/home/tommy/down [...]

2022-12-08 17:46 UTC, moratom commented on include/depthai/pipeline/datatype/NNData.hpp
> +
> CC: @moratom is there any features to bring over from rvc3, specifically "allocating" a tensor without copying the data just yet? Otherwise jot it down as a todo please & devise API

None as of yet, will devise the API today.

2022-12-13 13:49 UTC, themarpe commented
Thanks @whoactuallycares 

Do you mind putting this behind an optional `DEPTHAI_XTENSOR_SUPPORT` as is OpenCV? Though ON by default
Check ImgFrame on means of augmenting the API with that define + add it into `depthai-core/cmake/config.hpp.in` to denote its support.

2024-09-30 16:21 UTC, moratom commented
Merge to `v3_develop`

2024-09-30 16:21 UTC, closed without merging