add (demo, test) added demo code and the test
luxonis/depthai-core pull request #67
Opened 2021-02-25 13:49 UTC by Erol444

added cpp example and test

2021-02-25 13:50 UTC, szabi-luxonis approved these changes

2021-02-25 14:14 UTC, themarpe requested changes
Also try to stick to either `snake_case` or `camelCase` for variable names consistently through the example

2021-02-25 14:14 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +    detectionNetwork->setAnchors(anchors);
Use initializer lists for clearer usage
```
    // network specific!!
    detectionNetwork->setConfidenceThreshold(0.5f);
    detectionNetwork->setNumClasses(80);
    detectionNetwork->setCoordinateSize(4);
    detectionNetwork->setAnchors({10, 14, 23, 27, 37, 58, 81, 82, 135, 169, 344, 319});
    detectionNetwork->setAnchorMasks({{"side13", {1,2,3}}, {"side26", {3,4,5}}});
    detectionNetwork->setIouThreshold(0.5f);
```

2021-02-25 14:14 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +        float elapsed_s = std::chrono::duration_cast<std::chrono::milliseconds>(current_time-start_time).count() / 1000.;
Replace with:
```
auto elapsed = duration_cast<duration<float>>(current_time - start_time);
if (elapsed > seconds(1)){
    fps = counter / elapsed;
 ....
 ```

2021-02-25 14:14 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +    using namespace std;
Add:
```
using namespace std::chrono;
```

2021-02-25 14:14 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +            snprintf(conf_str, sizeof conf_str, "%.2f", d.confidence*100);
Preferably C++ish
```
std::stringstream s;
s << std::fixed << std::setprecision(2) << d.confidence*100;
// s.str();
```

2021-02-25 14:14 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +        char fps_str[15];
Same as above

2021-02-25 14:15 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +        float elapsed_s = std::chrono::duration_cast<std::chrono::milliseconds>(current_time-start_time).count() / 1000.;
The above creates a representation of seconds in float format. So below division will work as expected.
Otherwise, counter could be float and then no duration cast would be needed

2021-03-01 10:35 UTC, themarpe approved these changes
Feel free to merge after the extra change.
Thanks for the PR:)

2021-03-01 10:35 UTC, themarpe commented on examples/src/tiny_yolo_v3_device_side_decoding_example.cpp
> +            if(labelIndex < sizeof(label_map) / sizeof(label_map[0])) {
Rather do:
```
static const auto labelMap = { ... } // or static const std::vector<std::string> = { ... }
...
if(labelIndex < labelMap.size()) { 
...
}
```

2021-03-01 10:35 UTC, themarpe commented on examples/src/tiny_yolo_v4_device_side_decoding_example.cpp
> +            if(labelIndex < sizeof(label_map) / sizeof(label_map[0])) {
As above

2021-03-03 13:17 UTC, merged