Moved timestamps and sequence number from descendants to RawBuffer
luxonis/depthai-core pull request #890
Opened 2023-08-15 13:08 UTC by asahtik

Getters and setters for moved parameters in depthai-shared and changed (de)serialization.

2023-08-15 13:59 UTC, szabi-luxonis requested changes

2023-08-15 13:59 UTC, szabi-luxonis commented on src/pipeline/datatype/Buffer.cpp
> +    raw->ts.nsec = duration_cast<nanoseconds>(ts).count() % 1000000000;
should be `tsDevice`

2023-08-16 12:43 UTC, szabi-luxonis approved these changes
LGTM from my side

TODO: port generic sync node from rvc3

2023-08-16 14:17 UTC, themarpe requested changes
Looks like the rest of the messages still have `setTimestamp, etc...` functions.

For setters we'd have to CRTP (due to return type), but atleast getters can be removed cleanly
In derived setters, lets call parent & static_cast down cast then aka:
```
NNData& NNData::setTimestamp(std::chrono::time_point<std::chrono::steady_clock, std::chrono::steady_clock::duration> timestamp) {
    static_cast<NNData&>(Buffer::setTimestamp(timestamp));
}
```

2023-08-17 13:31 UTC, themarpe requested changes

2023-08-21 21:16 UTC, themarpe approved these changes
Update `depthai-core\cmake\Depthai\DepthaiDeviceSideConfig.cmake` FW version with updated FW that has this changes in as well

2023-08-31 01:21 UTC, merged