Add ISP 3A camera controls
luxonis/depthai-core pull request #9
Opened 2020-09-28 22:01 UTC by alex-luxonis

Depends on https://github.com/luxonis/depthai-shared/pull/5

2020-09-28 22:36 UTC, szabi-luxonis requested changes

2020-09-28 22:36 UTC, szabi-luxonis commented on src/host_capture_command.cpp
> +void HostCaptureCommand::sendIsp3A(int camera_id, int command_id, const char *extra_args) {
keep the interface 
```
Isp3A_CamId camera_id, Isp3A_Commands command_id,
                                const std::string &extra_args)
```
and do the neccessary conversion inside the function.

2020-09-28 22:39 UTC, szabi-luxonis commented on src/host_capture_command.cpp
> +void HostCaptureCommand::sendIsp3A(int camera_id, int command_id, const char *extra_args) {
Also, add support for empty `extra_args` string?

2020-10-06 00:02 UTC, themarpe requested changes

2020-10-06 02:01 UTC, alex-luxonis commented on src/host_capture_command.cpp
> +    cmd_data.data = (void*)cmdfull.c_str();
Yeah, `extra_args` is expected to be a string, space separated integers. I was going this way as there is already a camera-command string parser implemented on device side.

At some point we also need to merge the `CaptureMetadata` functionality with this one. Should we go like there? But need then to create separate functions for each command.

2020-10-06 13:33 UTC, themarpe commented on src/host_capture_command.cpp
> +    cmd_data.data = (void*)cmdfull.c_str();
If this CaptureMetadata is subset of ISP 3A then do integrate it.

One issue with just having these extra args there is that they are meaningless to users and they must seek description of this. 
Maybe in core create another class which actually knows how to deal with this data, which is then exposed to users. 

Eg. CameraControl in depthai-shared is only a means of describing data which is transferred between host & device and then in depthai-core create meaningful functions which use CameraControl as a means of sending type-safe commands&data

If you go about integrating CaptureMetadata, it will be an example of the need of having this extra layer IMO

2020-10-06 15:32 UTC, Luxonis-Brandon commented on src/host_capture_command.cpp
> +    cmd_data.data = (void*)cmdfull.c_str();
Thanks both!  Agreed good call to reduce support load by making these self-descriptive/discoverable.

So what I'm thinking is we add these improvements to the roadmap to do after we get subpixel/median/LR-Check-median/bilateral support out. 

The `why` is we are getting increasing pressure to get these out from a variety of customers, and the ISP-controls capability has already served the purposes of the two customers who needed it (in fact they don't need this power, they just needed EV compensation control on grayscale only).

Thoughts?

2020-10-07 21:15 UTC, merged