Message groups
luxonis/depthai-core pull request #917
Opened 2023-11-02 16:43 UTC by asahtik

Implemented Sync and MessageDemux nodes with the MessageGroup datatype.

2023-11-03 12:53 UTC, themarpe requested changes

2023-11-03 12:53 UTC, themarpe commented on include/depthai/pipeline/node/VideoEncoder.hpp
> +    Output out{*this, "out", Output::Type::MSender, {{DatatypeEnum::EncodedFrame, false}}};
Mutually exclusive between bitstream, correct? Do note it in comment if this is the case

2023-11-03 12:53 UTC, themarpe commented on include/depthai/pipeline/datatype/MessageGroup.hpp
> + * IMUData message. Carries normalized detection results
Update the comment

2023-11-03 12:53 UTC, themarpe commented on src/device/DataQueue.cpp
> +                    auto rawMsgGrp = std::dynamic_pointer_cast<RawMessageGroup>(data->serialize());
This seems unnecessary - static_cast (due to previous type check above) data itself and then access the underlying group variable directly (no need to "serialize" again)

2023-11-03 12:53 UTC, themarpe commented on src/device/DataQueue.cpp
> +                        msg.second.buffer = packets[msg.second.index]->serialize();
This seems like we are storing Raw* messages in MessageGroup? Group should preferably hold something along the lines of: `map<string, shared_ptr<ADatatype>>`

2023-11-03 12:53 UTC, themarpe commented on src/pipeline/datatype/MessageGroup.cpp
> +}
As per above comment - if we can make this not necessary, that'd be best 
(eg MessageGroup has no Raw* equivalent, but deals purely in core space - this will be inline with merging of core & shared as well)

2023-11-03 12:53 UTC, themarpe commented on include/depthai/pipeline/node/MessageDemux.hpp
> +    OutputMap outputs;
If MessageGroup can be "sync successful or not", perhaps might make sense having this also have a check here, to only demux on successful syncs, etc...

2023-11-03 12:53 UTC, themarpe commented on src/utility/H26xParsers.hpp
> +
```suggestion
namespace utility {
```

2023-11-03 12:53 UTC, themarpe commented on src/utility/H26xParsers.hpp
> +
```suggestion
}
```

2023-11-03 12:53 UTC, themarpe commented on src/utility/TypeToEnum.cpp
> +#include "depthai/utility/TypeToEnum.hpp"
Static field or using in message would be better. Note, conditional to structure of this as I've pointed out above, if its even necessary

2023-11-09 20:06 UTC, moratom commented on include/depthai/pipeline/node/Sync.hpp
> +    void setNumFramesPool(unsigned int numFramesPool);
@asahtik does the sync node need its own pools?

2023-11-10 07:26 UTC, asahtik commented on include/depthai/pipeline/node/Sync.hpp
> +    void setNumFramesPool(unsigned int numFramesPool);
It's for getting a MessageGroup object for storing the metadata (map, whether the sync was successful)

2023-11-10 11:22 UTC, moratom commented on include/depthai/pipeline/datatype/MessageGroup.hpp
> +
Add a method `getMessageNames` or something along these lines, since the map itself is private.

2023-11-10 11:26 UTC, moratom commented
Please add an example to `depthai-core` & `depthai-python` (Create a `Sync` sub-directory in `examples`)

2023-11-16 00:53 UTC, themarpe requested changes
Add a nice example of syncing eg: left & right imagers, etc... then sending on host & displaying both synced.

2023-11-16 00:53 UTC, themarpe commented on include/depthai/pipeline/datatype/MessageGroup.hpp
> +
IMO, rather expose more of the map like functionality altogether. But nice to have, non blocking, can be added later

2023-11-16 00:53 UTC, themarpe commented on include/depthai/pipeline/node/Sync.hpp
> +    void setNumFramesPool(unsigned int numFramesPool);
I think we should default to dynamic here (and later on we can replace with pools as we fully unabstract them, as part of the pipeline)

2023-11-20 00:30 UTC, moratom commented on examples/Sync/depth_video_synced.cpp
> +            cv::imshow(frm.first, imgFrm->getFrame());
Same nitpick for depth as in `depthai-python`

2023-11-20 00:40 UTC, moratom requested changes
Apart from the requested changes, looks great!

2023-11-20 00:40 UTC, moratom commented on src/pipeline/datatype/MessageGroup.cpp
> +}
Could we return a reference here to match how the unordered queue handles the operator?

Otherwise I'd use the `.at` method and (re) throw if no message is found, I think what will happen right now is we will return default ADatatype message in case the key does not exist.

2023-11-20 12:35 UTC, szabi-luxonis commented on include/depthai/pipeline/node/Sync.hpp
> +    Output out{*this, "out", Output::Type::MSender, {{DatatypeEnum::MessageGroup, false}}};
I guess should be renamed to `outputs` to match `inputs` format?

2023-11-20 13:07 UTC, themarpe commented on include/depthai/pipeline/node/Sync.hpp
> +    Output out{*this, "out", Output::Type::MSender, {{DatatypeEnum::MessageGroup, false}}};
`outputs` refers to a map usually, so I'd leave as `out` as it sends as single (albeit combined) message

2023-11-28 08:50 UTC, themarpe approved these changes

2023-11-28 09:02 UTC, moratom approved these changes

2023-11-29 10:55 UTC, merged