Integrated Intel's object tracker, added spatial object tracker
luxonis/depthai-core pull request #92
Opened 2021-03-25 19:43 UTC by szabi-luxonis

Integrated Intel's object tracker and added spatial object tracker.

Examples:
```
object_tracker_example.cpp : performs object tracking
spatial_object_tracker_example.cpp : performs object tracking with spatial data
```

2021-03-25 22:49 UTC, themarpe requested changes
Thanks for the PR!
Some changes/comments, otherwise looking good:)

2021-03-25 22:49 UTC, themarpe commented on examples/src/mobilenet_device_side_decoding_example.cpp
> +            fps = (float)counter / elapsed.count();
```
fps = counter / elapsed.count() // elapsed.count() is a float
```

2021-03-25 22:49 UTC, themarpe commented on include/depthai/pipeline/datatype/Tracklets.hpp
> +    std::vector<Tracklet>& tracklets;
Missing docstring.

2021-03-25 22:49 UTC, themarpe commented on include/depthai/pipeline/datatype/Tracklets.hpp
> +    std::vector<Tracklet>& getTracklets() const;
Missing `const`: 
(I'd just expose the `tracklets` 'property' instead of both) 
```
const std::vector<Tracklet>& getTracklets() const;
// and an non const overload
std::vector<Tracklet>& getTracklets();
```

2021-03-25 22:49 UTC, themarpe commented on include/depthai/pipeline/node/ObjectTracker.hpp
> +    Output passthroughDetections{*this, "passthroughDetections", Output::Type::MSender, {{DatatypeEnum::ImgFrame, false}}};
`{DatatypeEnum:ImgDetections}`

2021-03-25 22:49 UTC, themarpe commented on include/depthai/pipeline/node/ObjectTracker.hpp
> +#include "depthai/pipeline/datatype/Tracklets.hpp"
Move to line 4 for consistency

2021-03-25 22:49 UTC, themarpe commented on examples/src/spatial_object_tracker_example.cpp
> +        colorCam->preview.link(xoutRgb->input);
Style
```
if(syncNN) {
    objectTracker->passthroughFrame.link(xoutRgb->input);
} else {
    colorCam->preview.link(xoutRgb->input);
}
```

2021-03-30 16:20 UTC, szabi-luxonis commented on examples/src/mobilenet_device_side_decoding_example.cpp
> +    auto startTime = std::chrono::steady_clock::now();
Changed it in every file.

2021-03-30 16:20 UTC, szabi-luxonis commented on include/depthai/pipeline/datatype/Tracklets.hpp
> +    std::vector<Tracklet>& getTracklets() const;
removed

2021-03-30 21:57 UTC, themarpe approved these changes

2021-04-06 03:02 UTC, merged