Automatic crash dump retrieval
luxonis/depthai-core pull request #921
Opened 2023-11-08 15:28 UTC by asahtik

Automatic retrieval of a crash dump if a device side crash is detected.

2023-11-08 15:55 UTC, themarpe requested changes

2023-11-09 07:40 UTC, asahtik commented on src/device/DeviceBase.cpp
> +
Yes but I decided against that since the device initialization does some things that are not necessary for retrieving a crash dump which would result in confusing console prints and wouldn't be as seamless.

2023-11-09 07:40 UTC, asahtik commented on src/device/DeviceBase.cpp
> +
I can easily change it though if you think it would be better

2023-11-10 13:14 UTC, themarpe commented on src/device/DeviceBase.cpp
> +
> Yes but I decided against that since the device initialization does some things that are not necessary for retrieving a crash dump which would result in confusing console prints and wouldn't be as seamless.

What are some of these things? Perhaps we control this under the "lite" mode, where we also skip acquiring crashdump, etc...

Main reason being that this code can be rather brittle

2023-11-23 16:50 UTC, moratom approved these changes
Looks good to me.

2023-11-23 16:50 UTC, moratom commented on src/device/DeviceBase.cpp
> +    auto crashDumpPathStr = utility::getEnv("DEPTHAI_CRASHDUMP");
Add to the README.md

2023-11-28 08:47 UTC, themarpe approved these changes

2023-11-29 16:10 UTC, merged