Support for OAK-T
luxonis/depthai-core pull request #950
Opened 2024-01-17 15:08 UTC by zrezke

## Support for OAK-T
![Screenshot from 2024-01-17 16-07-20](https://github.com/luxonis/depthai-core/assets/59307111/2a33c2a6-3141-491d-ab83-5262505d71f9)

2024-01-19 14:31 UTC, themarpe requested changes

2024-01-19 14:31 UTC, themarpe commented on examples/Camera/thermal_cam.cpp
> +    thermal->setFps(25);
lets add a name and refer to this as "thermal" & `setCamera("thermal")`

Is set Fps needed? Lets add some comments to that places that are "required" / optional to configure, such that example is a bit more explanatory

2024-01-19 14:31 UTC, themarpe commented on examples/Camera/thermal_cam.cpp
> +            sprintf(text, "%.1f deg C", frameFp32.at<float>(mouseY, mouseX));
```suggestion
            snprintf(text, sizeof(text), "%.1f deg C", frameFp32.at<float>(mouseY, mouseX));
```

2024-01-19 14:31 UTC, themarpe commented on examples/Camera/thermal_cam.cpp
> +    thermal->setPreviewSize(width, height);
This might not always be the case (in future if we update the sensor on a new device for instance). Cannot the FW infer this and incoming ImgFrames carrying correct values?

2024-01-19 16:46 UTC, zrezke commented on examples/Camera/thermal_cam.cpp
> +    thermal->setPreviewSize(width, height);
Agree, I'll change it up, this is more or less a leftover from development, left on TODO. Will modify the behaviour of camera node to take into account the sensor resolution when selecting a preview width, height. Currently it's just a hardcoded default of 300x300. Other uses of width, height can be replaced by getWidth, getHeight.

2024-02-19 14:17 UTC, moratom requested changes

2024-02-20 13:27 UTC, moratom approved these changes

2024-02-20 13:43 UTC, themarpe approved these changes
LGTM - we might change to `Thermal` (separate node) later on CC: @moratom

2024-02-20 13:45 UTC, merged