Release 2.25.0
luxonis/depthai-core pull request #975
Opened 2024-03-06 14:36 UTC by moratom

2024-03-07 12:15 UTC, szabi-luxonis requested changes

2024-03-07 12:15 UTC, szabi-luxonis commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +     * Retrieves minimal y coordinate in milimeters
mi`ll`imeter

Also, technically in depth units, which is configurable parameter in stereo node. 

Smth like:

```suggestion
     * Retrieves minimal y coordinate in depth units (millimeter by default)
```

same for all the other

2024-03-07 12:15 UTC, szabi-luxonis commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +    PointCloudData& setMinZ(float val);
does this take effect? Does it make sense to set it?

2024-03-07 12:16 UTC, szabi-luxonis commented on include/depthai/pipeline/node/PointCloud.hpp
> +    Output passthroughDepth{*this, "passthroughDepth", Output::Type::MSender, {{DatatypeEnum::ImgFrame, false}}};
add setNumFramesPool API for properties setter

2024-03-07 12:38 UTC, moratom commented on src/pcl/PointCloudData.cpp
> +        cloud->points[i].y = -dataPtr[i].y;
@asahtik does PCL library expect a right hand coordinate system and we do left hand or vice versa?

The standard seems to be to use the right hand system with y value pointing down.

2024-03-07 13:01 UTC, moratom commented on include/depthai/pipeline/datatype/PointCloudData.hpp
> +    PointCloudData& setMinZ(float val);
It provides API completeness, for any potential future replay - since the current setup isn't to compute `minZ` on the fly but it is done during the pointcloud generation.

Since we don't have any PCL consumers as of right now, none of the setters provide any value (yet).

2024-03-07 13:02 UTC, moratom commented on src/pcl/PointCloudData.cpp
> +        cloud->points[i].y = -dataPtr[i].y;
Let's change the PCL to be right handed to not "stand" out compared to the other libraries and be consistent with the spatial calculator we already have.

2024-03-07 13:37 UTC, moratom commented on src/pipeline/datatype/PointCloudConfig.cpp
> +    cfg.transformationMatrix = {transformationMatrix[0][0],
At least on GCC this doesn't produce any warnings with the default `cmake --build build`

2024-03-07 13:38 UTC, moratom commented on src/pipeline/datatype/PointCloudConfig.cpp
> +    cfg.transformationMatrix = {transformationMatrix[0][0],
With clang there are warnings indeed, I'll address.

2024-03-08 10:56 UTC, moratom commented
@szabi-luxonis I resolved all the raised points

2024-03-08 11:56 UTC, szabi-luxonis approved these changes

2024-03-08 13:39 UTC, merged